package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseShopPingCartSet<M extends BaseShopPingCartSet<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer Id) {
		set("Id", Id);
	}

	public java.lang.Integer getId() {
		return get("Id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("User_Id", userId);
	}

	public java.lang.Integer getUserId() {
		return get("User_Id");
	}

	public void setShoppingwallproductId(java.lang.Integer shoppingwallproductId) {
		set("ShopPingWallProduct_Id", shoppingwallproductId);
	}

	public java.lang.Integer getShoppingwallproductId() {
		return get("ShopPingWallProduct_Id");
	}

	public void setSpecifications(java.lang.String Specifications) {
		set("Specifications", Specifications);
	}

	public java.lang.String getSpecifications() {
		return get("Specifications");
	}

	public void setColor(java.lang.String Color) {
		set("Color", Color);
	}

	public java.lang.String getColor() {
		return get("Color");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("Store_Id", storeId);
	}

	public java.lang.Integer getStoreId() {
		return get("Store_Id");
	}

	public void setNumber(java.lang.Integer Number) {
		set("Number", Number);
	}

	public java.lang.Integer getNumber() {
		return get("Number");
	}

}
