package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePFoodsave<M extends BasePFoodsave<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer Id) {
		set("Id", Id);
	}

	public java.lang.Integer getId() {
		return get("Id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("Store_Id", storeId);
	}

	public java.lang.Integer getStoreId() {
		return get("Store_Id");
	}

	public void setNumber(java.lang.Integer Number) {
		set("Number", Number);
	}

	public java.lang.Integer getNumber() {
		return get("Number");
	}

	public void setPrice(java.lang.Double Price) {
		set("Price", Price);
	}

	public java.lang.Double getPrice() {
		return get("Price");
	}

	public void setProductId(java.lang.Integer productId) {
		set("Product_Id", productId);
	}

	public java.lang.Integer getProductId() {
		return get("Product_Id");
	}

	public void setTypeId(java.lang.String TypeId) {
		set("TypeId", TypeId);
	}

	public java.lang.String getTypeId() {
		return get("TypeId");
	}

	public void setProductName(java.lang.String productName) {
		set("Product_Name", productName);
	}

	public java.lang.String getProductName() {
		return get("Product_Name");
	}

	public void setUserId(java.lang.Integer UserId) {
		set("UserId", UserId);
	}

	public java.lang.Integer getUserId() {
		return get("UserId");
	}

}
