package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIdentifyingCode<M extends BaseIdentifyingCode<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setTel(java.lang.String Tel) {
		set("Tel", Tel);
	}

	public java.lang.String getTel() {
		return get("Tel");
	}

	public void setCode(java.lang.String Code) {
		set("Code", Code);
	}

	public java.lang.String getCode() {
		return get("Code");
	}

	public void setOverTime(java.util.Date OverTime) {
		set("OverTime", OverTime);
	}

	public java.util.Date getOverTime() {
		return get("OverTime");
	}

}
