package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrderDetailsSet<M extends BaseOrderDetailsSet<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer Id) {
		set("Id", Id);
	}

	public java.lang.Integer getId() {
		return get("Id");
	}

	public void setOrderId(java.lang.Integer orderId) {
		set("Order_Id", orderId);
	}

	public java.lang.Integer getOrderId() {
		return get("Order_Id");
	}

	public void setProductId(java.lang.Integer productId) {
		set("Product_Id", productId);
	}

	public java.lang.Integer getProductId() {
		return get("Product_Id");
	}

	public void setRemarks(java.lang.String Remarks) {
		set("Remarks", Remarks);
	}

	public java.lang.String getRemarks() {
		return get("Remarks");
	}

	public void setCount(java.lang.Integer Count) {
		set("Count", Count);
	}

	public java.lang.Integer getCount() {
		return get("Count");
	}

	public void setPrice(java.lang.Double Price) {
		set("Price", Price);
	}

	public java.lang.Double getPrice() {
		return get("Price");
	}

	public void setOrderstate(java.lang.Integer orderstate) {
		set("orderstate", orderstate);
	}

	public java.lang.Integer getOrderstate() {
		return get("orderstate");
	}

}
