package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserAddressSet<M extends BaseUserAddressSet<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer Id) {
		set("Id", Id);
	}

	public java.lang.Integer getId() {
		return get("Id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("User_Id", userId);
	}

	public java.lang.Integer getUserId() {
		return get("User_Id");
	}

	public void setName(java.lang.String Name) {
		set("Name", Name);
	}

	public java.lang.String getName() {
		return get("Name");
	}

	public void setTelePhone(java.lang.String TelePhone) {
		set("TelePhone", TelePhone);
	}

	public java.lang.String getTelePhone() {
		return get("TelePhone");
	}

	public void setAddress(java.lang.String Address) {
		set("Address", Address);
	}

	public java.lang.String getAddress() {
		return get("Address");
	}

	public void setZipCode(java.lang.Integer ZipCode) {
		set("ZipCode", ZipCode);
	}

	public java.lang.Integer getZipCode() {
		return get("ZipCode");
	}

	public void setIsDefault(java.lang.Integer IsDefault) {
		set("IsDefault", IsDefault);
	}

	public java.lang.Integer getIsDefault() {
		return get("IsDefault");
	}

}
