package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTScanning<M extends BaseTScanning<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer Id) {
		set("Id", Id);
	}

	public java.lang.Integer getId() {
		return get("Id");
	}

	public void setTablenumber(java.lang.Integer Tablenumber) {
		set("Tablenumber", Tablenumber);
	}

	public java.lang.Integer getTablenumber() {
		return get("Tablenumber");
	}

	public void setProductId(java.lang.Integer productId) {
		set("product_id", productId);
	}

	public java.lang.Integer getProductId() {
		return get("product_id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}

	public java.lang.Integer getStoreId() {
		return get("store_id");
	}

	public void setNumber(java.lang.Integer number) {
		set("number", number);
	}

	public java.lang.Integer getNumber() {
		return get("number");
	}

	public void setPrice(java.lang.Double Price) {
		set("Price", Price);
	}

	public java.lang.Double getPrice() {
		return get("Price");
	}

	public void setMobilephoneID(java.lang.String MobilephoneID) {
		set("MobilephoneID", MobilephoneID);
	}

	public java.lang.String getMobilephoneID() {
		return get("MobilephoneID");
	}

}
