package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZUser<M extends BaseZUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}

	public java.lang.String getUsername() {
		return get("username");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public void setCreateTime(java.sql.Date createTime) {
		set("create_time", createTime);
	}

	public java.sql.Date getCreateTime() {
		return get("create_time");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setNickname(java.lang.String nickname) {
		set("nickname", nickname);
	}

	public java.lang.String getNickname() {
		return get("nickname");
	}

	public void setImg(java.lang.String img) {
		set("img", img);
	}

	public java.lang.String getImg() {
		return get("img");
	}

	public void setSex(java.lang.Integer sex) {
		set("sex", sex);
	}

	public java.lang.Integer getSex() {
		return get("sex");
	}

	public void setGetname(java.lang.String getname) {
		set("getname", getname);
	}

	public java.lang.String getGetname() {
		return get("getname");
	}

	public void setGettel(java.lang.String gettel) {
		set("gettel", gettel);
	}

	public java.lang.String getGettel() {
		return get("gettel");
	}

	public void setGetadr(java.lang.String getadr) {
		set("getadr", getadr);
	}

	public java.lang.String getGetadr() {
		return get("getadr");
	}

	public void setGetzipcode(java.lang.String getzipcode) {
		set("getzipcode", getzipcode);
	}

	public java.lang.String getGetzipcode() {
		return get("getzipcode");
	}

	public void setPaperImg(java.lang.String paperImg) {
		set("paper_img", paperImg);
	}

	public java.lang.String getPaperImg() {
		return get("paper_img");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setScore(java.lang.Integer score) {
		set("score", score);
	}

	public java.lang.Integer getScore() {
		return get("score");
	}

	public void setIdentity(java.lang.Integer identity) {
		set("identity", identity);
	}

	public java.lang.Integer getIdentity() {
		return get("identity");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public void setQq(java.lang.String qq) {
		set("qq", qq);
	}

	public java.lang.String getQq() {
		return get("qq");
	}

	public void setIdentiticard(java.lang.String identiticard) {
		set("identiticard", identiticard);
	}

	public java.lang.String getIdentiticard() {
		return get("identiticard");
	}

	public void setInvitetelephone(java.lang.String invitetelephone) {
		set("invitetelephone", invitetelephone);
	}

	public java.lang.String getInvitetelephone() {
		return get("invitetelephone");
	}

	public void setExaminestate(java.lang.Integer examinestate) {
		set("examinestate", examinestate);
	}

	public java.lang.Integer getExaminestate() {
		return get("examinestate");
	}

	public void setOnlinestate(java.lang.Boolean onlinestate) {
		set("onlinestate", onlinestate);
	}

	public java.lang.Boolean getOnlinestate() {
		return get("onlinestate");
	}

	public void setUsernumber(java.lang.String usernumber) {
		set("usernumber", usernumber);
	}

	public java.lang.String getUsernumber() {
		return get("usernumber");
	}

	public void setMoney(java.math.BigDecimal money) {
		set("money", money);
	}

	public java.math.BigDecimal getMoney() {
		return get("money");
	}

}
