package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZTravelGuide<M extends BaseZTravelGuide<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}

	public java.lang.String getUsername() {
		return get("username");
	}

	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}

	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public void setHours(java.lang.Integer hours) {
		set("hours", hours);
	}

	public java.lang.Integer getHours() {
		return get("hours");
	}

	public void setProvinceId(java.lang.Integer provinceId) {
		set("province_id", provinceId);
	}

	public java.lang.Integer getProvinceId() {
		return get("province_id");
	}

	public void setCityId(java.lang.Integer cityId) {
		set("city_id", cityId);
	}

	public java.lang.Integer getCityId() {
		return get("city_id");
	}

	public void setCountyId(java.lang.Integer countyId) {
		set("county_id", countyId);
	}

	public java.lang.Integer getCountyId() {
		return get("county_id");
	}

	public void setConfigure(java.lang.String configure) {
		set("configure", configure);
	}

	public java.lang.String getConfigure() {
		return get("configure");
	}

	public void setPlaces(java.lang.String places) {
		set("places", places);
	}

	public java.lang.String getPlaces() {
		return get("places");
	}

	public void setCarC(java.lang.Integer carC) {
		set("car_c", carC);
	}

	public java.lang.Integer getCarC() {
		return get("car_c");
	}

	public void setCarBrand(java.lang.String carBrand) {
		set("car_brand", carBrand);
	}

	public java.lang.String getCarBrand() {
		return get("car_brand");
	}

	public void setCarCate(java.lang.String carCate) {
		set("car_cate", carCate);
	}

	public java.lang.String getCarCate() {
		return get("car_cate");
	}

	public void setCarPrice(java.math.BigDecimal carPrice) {
		set("car_price", carPrice);
	}

	public java.math.BigDecimal getCarPrice() {
		return get("car_price");
	}

	public void setCarHours(java.lang.Integer carHours) {
		set("car_hours", carHours);
	}

	public java.lang.Integer getCarHours() {
		return get("car_hours");
	}

	public void setMessage(java.lang.String message) {
		set("message", message);
	}

	public java.lang.String getMessage() {
		return get("message");
	}

	public void setTelephone(java.lang.String telephone) {
		set("telephone", telephone);
	}

	public java.lang.String getTelephone() {
		return get("telephone");
	}

	public void setCreateTime(java.sql.Date createTime) {
		set("create_time", createTime);
	}

	public java.sql.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.sql.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.sql.Date getUpdateTime() {
		return get("update_time");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setLocationX(java.lang.String locationX) {
		set("location_x", locationX);
	}

	public java.lang.String getLocationX() {
		return get("location_x");
	}

	public void setLocationY(java.lang.String locationY) {
		set("location_y", locationY);
	}

	public java.lang.String getLocationY() {
		return get("location_y");
	}

	public void setSex(java.lang.Integer sex) {
		set("sex", sex);
	}

	public java.lang.Integer getSex() {
		return get("sex");
	}

	public void setAge(java.lang.Integer age) {
		set("age", age);
	}

	public java.lang.Integer getAge() {
		return get("age");
	}

	public void setUserStatus(java.lang.Integer userStatus) {
		set("user_status", userStatus);
	}

	public java.lang.Integer getUserStatus() {
		return get("user_status");
	}

}
