package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZcCarforpeople<M extends BaseZcCarforpeople<M>> extends Model<M> implements IBean {

	public void setCarforpeopleid(java.lang.Integer Carforpeopleid) {
		set("Carforpeopleid", Carforpeopleid);
	}

	public java.lang.Integer getCarforpeopleid() {
		return get("Carforpeopleid");
	}

	public void setPicture(java.lang.String picture) {
		set("picture", picture);
	}

	public java.lang.String getPicture() {
		return get("picture");
	}

	public void setStartingPoint(java.lang.String StartingPoint) {
		set("StartingPoint", StartingPoint);
	}

	public java.lang.String getStartingPoint() {
		return get("StartingPoint");
	}

	public void setArriving(java.lang.String Arriving) {
		set("Arriving", Arriving);
	}

	public java.lang.String getArriving() {
		return get("Arriving");
	}

	public void setDeparturetime(java.util.Date Departuretime) {
		set("Departuretime", Departuretime);
	}

	public java.util.Date getDeparturetime() {
		return get("Departuretime");
	}

	public void setJizou(java.lang.Integer Jizou) {
		set("Jizou", Jizou);
	}

	public java.lang.Integer getJizou() {
		return get("Jizou");
	}

	public void setLoop(java.lang.Integer loop) {
		set("loop", loop);
	}

	public java.lang.Integer getLoop() {
		return get("loop");
	}

	public void setThenumber(java.lang.Integer Thenumber) {
		set("Thenumber", Thenumber);
	}

	public java.lang.Integer getThenumber() {
		return get("Thenumber");
	}

	public void setCost(java.lang.String Cost) {
		set("Cost", Cost);
	}

	public java.lang.String getCost() {
		return get("Cost");
	}

	public void setAdditional(java.lang.String Additional) {
		set("Additional", Additional);
	}

	public java.lang.String getAdditional() {
		return get("Additional");
	}

	public void setVia(java.lang.String Via) {
		set("Via", Via);
	}

	public java.lang.String getVia() {
		return get("Via");
	}

	public void setCartype(java.lang.String Cartype) {
		set("Cartype", Cartype);
	}

	public java.lang.String getCartype() {
		return get("Cartype");
	}

	public void setLicenseplate(java.lang.String Licenseplate) {
		set("Licenseplate", Licenseplate);
	}

	public java.lang.String getLicenseplate() {
		return get("Licenseplate");
	}

	public void setContacts(java.lang.String Contacts) {
		set("Contacts", Contacts);
	}

	public java.lang.String getContacts() {
		return get("Contacts");
	}

	public void setSex(java.lang.Integer Sex) {
		set("Sex", Sex);
	}

	public java.lang.Integer getSex() {
		return get("Sex");
	}

	public void setDriving(java.lang.Integer Driving) {
		set("Driving", Driving);
	}

	public java.lang.Integer getDriving() {
		return get("Driving");
	}

	public void setTelephone(java.lang.String Telephone) {
		set("Telephone", Telephone);
	}

	public java.lang.String getTelephone() {
		return get("Telephone");
	}

	public void setPostscript(java.lang.String Postscript) {
		set("Postscript", Postscript);
	}

	public java.lang.String getPostscript() {
		return get("Postscript");
	}

	public void setDeposit(java.lang.String Deposit) {
		set("Deposit", Deposit);
	}

	public java.lang.String getDeposit() {
		return get("Deposit");
	}

	public void setReleasetime(java.lang.String Releasetime) {
		set("Releasetime", Releasetime);
	}

	public java.lang.String getReleasetime() {
		return get("Releasetime");
	}

}
