package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZcPeoplecar<M extends BaseZcPeoplecar<M>> extends Model<M> implements IBean {

	public void setPeopleCarid(java.lang.Integer PeopleCarid) {
		set("PeopleCarid", PeopleCarid);
	}

	public java.lang.Integer getPeopleCarid() {
		return get("PeopleCarid");
	}

	public void setPicture(java.lang.String picture) {
		set("picture", picture);
	}

	public java.lang.String getPicture() {
		return get("picture");
	}

	public void setStartingPoint(java.lang.String StartingPoint) {
		set("StartingPoint", StartingPoint);
	}

	public java.lang.String getStartingPoint() {
		return get("StartingPoint");
	}

	public void setArriving(java.lang.String Arriving) {
		set("Arriving", Arriving);
	}

	public java.lang.String getArriving() {
		return get("Arriving");
	}

	public void setDeparturetime(java.util.Date Departuretime) {
		set("Departuretime", Departuretime);
	}

	public java.util.Date getDeparturetime() {
		return get("Departuretime");
	}

	public void setJizou(java.lang.Integer Jizou) {
		set("Jizou", Jizou);
	}

	public java.lang.Integer getJizou() {
		return get("Jizou");
	}

	public void setCartype(java.lang.String Cartype) {
		set("Cartype", Cartype);
	}

	public java.lang.String getCartype() {
		return get("Cartype");
	}

	public void setAdditional(java.lang.String Additional) {
		set("Additional", Additional);
	}

	public java.lang.String getAdditional() {
		return get("Additional");
	}

	public void setContacts(java.lang.String Contacts) {
		set("Contacts", Contacts);
	}

	public java.lang.String getContacts() {
		return get("Contacts");
	}

	public void setSex(java.lang.Integer Sex) {
		set("Sex", Sex);
	}

	public java.lang.Integer getSex() {
		return get("Sex");
	}

	public void setTelephone(java.lang.String Telephone) {
		set("Telephone", Telephone);
	}

	public java.lang.String getTelephone() {
		return get("Telephone");
	}

	public void setPostscript(java.lang.String Postscript) {
		set("Postscript", Postscript);
	}

	public java.lang.String getPostscript() {
		return get("Postscript");
	}

	public void setReleasetime(java.lang.String Releasetime) {
		set("Releasetime", Releasetime);
	}

	public java.lang.String getReleasetime() {
		return get("Releasetime");
	}

}
