package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseShoppingWallProductSet<M extends BaseShoppingWallProductSet<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer Id) {
		set("Id", Id);
	}

	public java.lang.Integer getId() {
		return get("Id");
	}

	public void setName(java.lang.String Name) {
		set("Name", Name);
	}

	public java.lang.String getName() {
		return get("Name");
	}

	public void setDescription(java.lang.String Description) {
		set("Description", Description);
	}

	public java.lang.String getDescription() {
		return get("Description");
	}

	public void setPhoto(java.lang.String Photo) {
		set("Photo", Photo);
	}

	public java.lang.String getPhoto() {
		return get("Photo");
	}

	public void setPrice(java.lang.String Price) {
		set("Price", Price);
	}

	public java.lang.String getPrice() {
		return get("Price");
	}

	public void setProducttypeId(java.lang.Integer producttypeId) {
		set("ProductType_Id", producttypeId);
	}

	public java.lang.Integer getProducttypeId() {
		return get("ProductType_Id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("Store_Id", storeId);
	}

	public java.lang.Integer getStoreId() {
		return get("Store_Id");
	}

	public void setInTime(java.util.Date inTime) {
		set("inTime", inTime);
	}

	public java.util.Date getInTime() {
		return get("inTime");
	}

	public void setNotice(java.lang.String Notice) {
		set("Notice", Notice);
	}

	public java.lang.String getNotice() {
		return get("Notice");
	}

	public void setCompName(java.lang.String CompName) {
		set("CompName", CompName);
	}

	public java.lang.String getCompName() {
		return get("CompName");
	}

	public void setTel(java.lang.String Tel) {
		set("Tel", Tel);
	}

	public java.lang.String getTel() {
		return get("Tel");
	}

	public void setEmailPhoto(java.lang.String EmailPhoto) {
		set("EmailPhoto", EmailPhoto);
	}

	public java.lang.String getEmailPhoto() {
		return get("EmailPhoto");
	}

	public void setHTML(java.lang.String HTML) {
		set("HTML", HTML);
	}

	public java.lang.String getHTML() {
		return get("HTML");
	}

	public void setState(java.lang.String State) {
		set("State", State);
	}

	public java.lang.String getState() {
		return get("State");
	}

	public void setStock(java.lang.Integer stock) {
		set("stock", stock);
	}

	public java.lang.Integer getStock() {
		return get("stock");
	}

	public void setShopingWallSpecificationsTypeID(java.lang.Integer ShopingWallSpecificationsTypeID) {
		set("ShopingWallSpecificationsTypeID", ShopingWallSpecificationsTypeID);
	}

	public java.lang.Integer getShopingWallSpecificationsTypeID() {
		return get("ShopingWallSpecificationsTypeID");
	}

	public void setEPrice(java.lang.String EPrice) {
		set("EPrice", EPrice);
	}

	public java.lang.String getEPrice() {
		return get("EPrice");
	}

}
