package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZFindworker<M extends BaseZFindworker<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setProvinceId(java.lang.Integer provinceId) {
		set("province_id", provinceId);
	}

	public java.lang.Integer getProvinceId() {
		return get("province_id");
	}

	public void setCityId(java.lang.Integer cityId) {
		set("city_id", cityId);
	}

	public java.lang.Integer getCityId() {
		return get("city_id");
	}

	public void setCountyId(java.lang.Integer countyId) {
		set("county_id", countyId);
	}

	public java.lang.Integer getCountyId() {
		return get("county_id");
	}

	public void setSex(java.lang.Integer sex) {
		set("sex", sex);
	}

	public java.lang.Integer getSex() {
		return get("sex");
	}

	public void setAge(java.lang.String age) {
		set("age", age);
	}

	public java.lang.String getAge() {
		return get("age");
	}

	public void setIncome(java.lang.String income) {
		set("income", income);
	}

	public java.lang.String getIncome() {
		return get("income");
	}

	public void setChoice(java.lang.String choice) {
		set("choice", choice);
	}

	public java.lang.String getChoice() {
		return get("choice");
	}

	public void setRestday(java.lang.String restday) {
		set("restday", restday);
	}

	public java.lang.String getRestday() {
		return get("restday");
	}

	public void setWorktime(java.lang.String worktime) {
		set("worktime", worktime);
	}

	public java.lang.String getWorktime() {
		return get("worktime");
	}

	public void setDegrees(java.lang.String degrees) {
		set("degrees", degrees);
	}

	public java.lang.String getDegrees() {
		return get("degrees");
	}

	public void setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
	}

	public java.lang.String getRemarks() {
		return get("remarks");
	}

	public void setImgs(java.lang.String imgs) {
		set("imgs", imgs);
	}

	public java.lang.String getImgs() {
		return get("imgs");
	}

	public void setLinkman(java.lang.String linkman) {
		set("linkman", linkman);
	}

	public java.lang.String getLinkman() {
		return get("linkman");
	}

	public void setTel(java.lang.String tel) {
		set("tel", tel);
	}

	public java.lang.String getTel() {
		return get("tel");
	}

	public void setShowtel(java.lang.Integer showtel) {
		set("showtel", showtel);
	}

	public java.lang.Integer getShowtel() {
		return get("showtel");
	}

	public void setShowcontact(java.lang.Integer showcontact) {
		set("showcontact", showcontact);
	}

	public java.lang.Integer getShowcontact() {
		return get("showcontact");
	}

	public void setCreatetime(java.sql.Date createtime) {
		set("createtime", createtime);
	}

	public java.sql.Date getCreatetime() {
		return get("createtime");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public void setCompanyname(java.lang.String companyname) {
		set("companyname", companyname);
	}

	public java.lang.String getCompanyname() {
		return get("companyname");
	}

	public void setTrade(java.lang.String trade) {
		set("trade", trade);
	}

	public java.lang.String getTrade() {
		return get("trade");
	}

	public void setIntroduce(java.lang.String introduce) {
		set("introduce", introduce);
	}

	public java.lang.String getIntroduce() {
		return get("introduce");
	}

	public void setNums(java.lang.String nums) {
		set("nums", nums);
	}

	public java.lang.String getNums() {
		return get("nums");
	}

}
