package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBankCardList<M extends BaseBankCardList<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setUserId(java.lang.Integer UserId) {
		set("UserId", UserId);
	}

	public java.lang.Integer getUserId() {
		return get("UserId");
	}

	public void setBankType(java.lang.Integer bankType) {
		set("bankType", bankType);
	}

	public java.lang.Integer getBankType() {
		return get("bankType");
	}

	public void setBankName(java.lang.String bankName) {
		set("bankName", bankName);
	}

	public java.lang.String getBankName() {
		return get("bankName");
	}

	public void setBankCode(java.lang.String bankCode) {
		set("bankCode", bankCode);
	}

	public java.lang.String getBankCode() {
		return get("bankCode");
	}

	public void setBankUserName(java.lang.String bankUserName) {
		set("bankUserName", bankUserName);
	}

	public java.lang.String getBankUserName() {
		return get("bankUserName");
	}

	public void setBankProvince(java.lang.String bankProvince) {
		set("bankProvince", bankProvince);
	}

	public java.lang.String getBankProvince() {
		return get("bankProvince");
	}

	public void setBankCity(java.lang.String bankCity) {
		set("bankCity", bankCity);
	}

	public java.lang.String getBankCity() {
		return get("bankCity");
	}

	public void setBankArea(java.lang.String bankArea) {
		set("bankArea", bankArea);
	}

	public java.lang.String getBankArea() {
		return get("bankArea");
	}

	public void setBankAddress(java.lang.String bankAddress) {
		set("bankAddress", bankAddress);
	}

	public java.lang.String getBankAddress() {
		return get("bankAddress");
	}

	public void setUserTel(java.lang.String UserTel) {
		set("UserTel", UserTel);
	}

	public java.lang.String getUserTel() {
		return get("UserTel");
	}

}
