package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStoreValueSet<M extends BaseStoreValueSet<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer Id) {
		set("Id", Id);
	}

	public java.lang.Integer getId() {
		return get("Id");
	}

	public void setValue(java.lang.String Value) {
		set("Value", Value);
	}

	public java.lang.String getValue() {
		return get("Value");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("Store_Id", storeId);
	}

	public java.lang.Integer getStoreId() {
		return get("Store_Id");
	}

	public void setStorepropertyId(java.lang.Integer storepropertyId) {
		set("StoreProperty_Id", storepropertyId);
	}

	public java.lang.Integer getStorepropertyId() {
		return get("StoreProperty_Id");
	}

}
