package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseShopPingProductOrderSet<M extends BaseShopPingProductOrderSet<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer Id) {
		set("Id", Id);
	}

	public java.lang.Integer getId() {
		return get("Id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("Store_Id", storeId);
	}

	public java.lang.Integer getStoreId() {
		return get("Store_Id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("User_Id", userId);
	}

	public java.lang.Integer getUserId() {
		return get("User_Id");
	}

	public void setRemarks(java.lang.String Remarks) {
		set("Remarks", Remarks);
	}

	public java.lang.String getRemarks() {
		return get("Remarks");
	}

	public void setPlaceOrderTime(java.util.Date PlaceOrderTime) {
		set("PlaceOrderTime", PlaceOrderTime);
	}

	public java.util.Date getPlaceOrderTime() {
		return get("PlaceOrderTime");
	}

	public void setExamineTime(java.util.Date ExamineTime) {
		set("ExamineTime", ExamineTime);
	}

	public java.util.Date getExamineTime() {
		return get("ExamineTime");
	}

	public void setArriveTime(java.util.Date ArriveTime) {
		set("ArriveTime", ArriveTime);
	}

	public java.util.Date getArriveTime() {
		return get("ArriveTime");
	}

	public void setFreight(java.lang.Double Freight) {
		set("Freight", Freight);
	}

	public java.lang.Double getFreight() {
		return get("Freight");
	}

	public void setLslnvoice(java.lang.Boolean lslnvoice) {
		set("lslnvoice", lslnvoice);
	}

	public java.lang.Boolean getLslnvoice() {
		return get("lslnvoice");
	}

	public void setCourierMethod(java.lang.String CourierMethod) {
		set("CourierMethod", CourierMethod);
	}

	public java.lang.String getCourierMethod() {
		return get("CourierMethod");
	}

	public void setState(java.lang.Integer State) {
		set("State", State);
	}

	public java.lang.Integer getState() {
		return get("State");
	}

	public void setPaymentMethod(java.lang.String PaymentMethod) {
		set("PaymentMethod", PaymentMethod);
	}

	public java.lang.String getPaymentMethod() {
		return get("PaymentMethod");
	}

	public void setShopPingProductOrderType(java.lang.Integer ShopPingProductOrderType) {
		set("ShopPingProductOrderType", ShopPingProductOrderType);
	}

	public java.lang.Integer getShopPingProductOrderType() {
		return get("ShopPingProductOrderType");
	}

	public void setSumPrice(java.lang.Double SumPrice) {
		set("SumPrice", SumPrice);
	}

	public java.lang.Double getSumPrice() {
		return get("SumPrice");
	}

}
