package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrderSet<M extends BaseOrderSet<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer Id) {
		set("Id", Id);
	}

	public java.lang.Integer getId() {
		return get("Id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("Store_Id", storeId);
	}

	public java.lang.Integer getStoreId() {
		return get("Store_Id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("User_Id", userId);
	}

	public java.lang.Integer getUserId() {
		return get("User_Id");
	}

	public void setRemarks(java.lang.String Remarks) {
		set("Remarks", Remarks);
	}

	public java.lang.String getRemarks() {
		return get("Remarks");
	}

	public void setPlaceOrderTime(java.util.Date PlaceOrderTime) {
		set("PlaceOrderTime", PlaceOrderTime);
	}

	public java.util.Date getPlaceOrderTime() {
		return get("PlaceOrderTime");
	}

	public void setExamineTime(java.util.Date ExamineTime) {
		set("ExamineTime", ExamineTime);
	}

	public java.util.Date getExamineTime() {
		return get("ExamineTime");
	}

	public void setArriveTime(java.util.Date ArriveTime) {
		set("ArriveTime", ArriveTime);
	}

	public java.util.Date getArriveTime() {
		return get("ArriveTime");
	}

	public void setFreight(java.lang.Double Freight) {
		set("Freight", Freight);
	}

	public java.lang.Double getFreight() {
		return get("Freight");
	}

	public void setIsInvoice(java.lang.Boolean IsInvoice) {
		set("IsInvoice", IsInvoice);
	}

	public java.lang.Boolean getIsInvoice() {
		return get("IsInvoice");
	}

	public void setState(java.lang.Integer State) {
		set("State", State);
	}

	public java.lang.Integer getState() {
		return get("State");
	}

	public void setCourierMethod(java.lang.String CourierMethod) {
		set("CourierMethod", CourierMethod);
	}

	public java.lang.String getCourierMethod() {
		return get("CourierMethod");
	}

	public void setPaymentMethod(java.lang.String PaymentMethod) {
		set("PaymentMethod", PaymentMethod);
	}

	public java.lang.String getPaymentMethod() {
		return get("PaymentMethod");
	}

	public void setUseraddressId(java.lang.Integer useraddressId) {
		set("UserAddress_Id", useraddressId);
	}

	public java.lang.Integer getUseraddressId() {
		return get("UserAddress_Id");
	}

	public void setOrderType(java.lang.Integer OrderType) {
		set("OrderType", OrderType);
	}

	public java.lang.Integer getOrderType() {
		return get("OrderType");
	}

	public void setSumPrice(java.lang.Double SumPrice) {
		set("SumPrice", SumPrice);
	}

	public java.lang.Double getSumPrice() {
		return get("SumPrice");
	}

	public void setReserveOrderId(java.lang.Integer ReserveOrderId) {
		set("ReserveOrderId", ReserveOrderId);
	}

	public java.lang.Integer getReserveOrderId() {
		return get("ReserveOrderId");
	}

	public void setIsPrint(java.lang.Integer IsPrint) {
		set("IsPrint", IsPrint);
	}

	public java.lang.Integer getIsPrint() {
		return get("IsPrint");
	}

	public void setIsDelete(java.lang.Integer IsDelete) {
		set("IsDelete", IsDelete);
	}

	public java.lang.Integer getIsDelete() {
		return get("IsDelete");
	}

}
