package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAdvertisementTable<M extends BaseAdvertisementTable<M>> extends Model<M> implements IBean {

	public void setAdvertisementId(java.lang.Integer AdvertisementId) {
		set("AdvertisementId", AdvertisementId);
	}

	public java.lang.Integer getAdvertisementId() {
		return get("AdvertisementId");
	}

	public void setUserId(java.lang.Integer UserId) {
		set("UserId", UserId);
	}

	public java.lang.Integer getUserId() {
		return get("UserId");
	}

	public void setWrittenWords(java.lang.String WrittenWords) {
		set("WrittenWords", WrittenWords);
	}

	public java.lang.String getWrittenWords() {
		return get("WrittenWords");
	}

	public void setPicture(java.lang.String Picture) {
		set("Picture", Picture);
	}

	public java.lang.String getPicture() {
		return get("Picture");
	}

	public void setLongitude(java.lang.Double Longitude) {
		set("Longitude", Longitude);
	}

	public java.lang.Double getLongitude() {
		return get("Longitude");
	}

	public void setLatitude(java.lang.Double Latitude) {
		set("Latitude", Latitude);
	}

	public java.lang.Double getLatitude() {
		return get("Latitude");
	}

	public void setAdtypes(java.lang.Integer Adtypes) {
		set("Adtypes", Adtypes);
	}

	public java.lang.Integer getAdtypes() {
		return get("Adtypes");
	}

	public void setModuleClass(java.lang.Integer ModuleClass) {
		set("ModuleClass", ModuleClass);
	}

	public java.lang.Integer getModuleClass() {
		return get("ModuleClass");
	}

	public void setCreatetime(java.util.Date Createtime) {
		set("Createtime", Createtime);
	}

	public java.util.Date getCreatetime() {
		return get("Createtime");
	}

	public void setExpiredtime(java.util.Date Expiredtime) {
		set("Expiredtime", Expiredtime);
	}

	public java.util.Date getExpiredtime() {
		return get("Expiredtime");
	}

	public void setAdvertisementType(java.lang.Integer AdvertisementType) {
		set("AdvertisementType", AdvertisementType);
	}

	public java.lang.Integer getAdvertisementType() {
		return get("AdvertisementType");
	}

	public void setAdvertisementAddress(java.lang.String AdvertisementAddress) {
		set("AdvertisementAddress", AdvertisementAddress);
	}

	public java.lang.String getAdvertisementAddress() {
		return get("AdvertisementAddress");
	}

	public void setLink(java.lang.String link) {
		set("link", link);
	}

	public java.lang.String getLink() {
		return get("link");
	}

}
