package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFriendTable<M extends BaseFriendTable<M>> extends Model<M> implements IBean {

	public void setFriendId(java.lang.Integer FriendId) {
		set("FriendId", FriendId);
	}

	public java.lang.Integer getFriendId() {
		return get("FriendId");
	}

	public void setUserId(java.lang.Integer UserId) {
		set("UserId", UserId);
	}

	public java.lang.Integer getUserId() {
		return get("UserId");
	}

	public void setFriends(java.lang.Integer Friends) {
		set("Friends", Friends);
	}

	public java.lang.Integer getFriends() {
		return get("Friends");
	}

	public void setGroupingId(java.lang.Integer GroupingId) {
		set("GroupingId", GroupingId);
	}

	public java.lang.Integer getGroupingId() {
		return get("GroupingId");
	}

	public void setState(java.lang.Integer State) {
		set("State", State);
	}

	public java.lang.Integer getState() {
		return get("State");
	}

	public void setIsBlacklist(java.lang.Integer IsBlacklist) {
		set("IsBlacklist", IsBlacklist);
	}

	public java.lang.Integer getIsBlacklist() {
		return get("IsBlacklist");
	}

}
