package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZcCarandgoods<M extends BaseZcCarandgoods<M>> extends Model<M> implements IBean {

	public void setCarAndgoodsid(java.lang.Integer CarAndgoodsid) {
		set("CarAndgoodsid", CarAndgoodsid);
	}

	public java.lang.Integer getCarAndgoodsid() {
		return get("CarAndgoodsid");
	}

	public void setPicture(java.lang.String picture) {
		set("picture", picture);
	}

	public java.lang.String getPicture() {
		return get("picture");
	}

	public void setStartingPoint(java.lang.String StartingPoint) {
		set("StartingPoint", StartingPoint);
	}

	public java.lang.String getStartingPoint() {
		return get("StartingPoint");
	}

	public void setArriving(java.lang.String Arriving) {
		set("Arriving", Arriving);
	}

	public java.lang.String getArriving() {
		return get("Arriving");
	}

	public void setAdditional(java.lang.String Additional) {
		set("Additional", Additional);
	}

	public java.lang.String getAdditional() {
		return get("Additional");
	}

	public void setDeparturetime(java.util.Date Departuretime) {
		set("Departuretime", Departuretime);
	}

	public java.util.Date getDeparturetime() {
		return get("Departuretime");
	}

	public void setJizou(java.lang.Integer Jizou) {
		set("Jizou", Jizou);
	}

	public java.lang.Integer getJizou() {
		return get("Jizou");
	}

	public void setBearing(java.lang.String Bearing) {
		set("Bearing", Bearing);
	}

	public java.lang.String getBearing() {
		return get("Bearing");
	}

	public void setSpace(java.lang.String Space) {
		set("Space", Space);
	}

	public java.lang.String getSpace() {
		return get("Space");
	}

	public void setCost(java.lang.String Cost) {
		set("Cost", Cost);
	}

	public java.lang.String getCost() {
		return get("Cost");
	}

	public void setVia(java.lang.String Via) {
		set("Via", Via);
	}

	public java.lang.String getVia() {
		return get("Via");
	}

	public void setContacts(java.lang.String Contacts) {
		set("Contacts", Contacts);
	}

	public java.lang.String getContacts() {
		return get("Contacts");
	}

	public void setSex(java.lang.Integer Sex) {
		set("Sex", Sex);
	}

	public java.lang.Integer getSex() {
		return get("Sex");
	}

	public void setDriving(java.lang.Integer Driving) {
		set("Driving", Driving);
	}

	public java.lang.Integer getDriving() {
		return get("Driving");
	}

	public void setTelephone(java.lang.String Telephone) {
		set("Telephone", Telephone);
	}

	public java.lang.String getTelephone() {
		return get("Telephone");
	}

	public void setPostscript(java.lang.String Postscript) {
		set("Postscript", Postscript);
	}

	public java.lang.String getPostscript() {
		return get("Postscript");
	}

	public void setDeposit(java.lang.String Deposit) {
		set("Deposit", Deposit);
	}

	public java.lang.String getDeposit() {
		return get("Deposit");
	}

	public void setReleasetime(java.lang.String Releasetime) {
		set("Releasetime", Releasetime);
	}

	public java.lang.String getReleasetime() {
		return get("Releasetime");
	}

	public void setCpany(java.lang.Integer Cpany) {
		set("Cpany", Cpany);
	}

	public java.lang.Integer getCpany() {
		return get("Cpany");
	}

}
