package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMessage<M extends BaseMessage<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer Id) {
		set("Id", Id);
	}

	public java.lang.Integer getId() {
		return get("Id");
	}

	public void setContents(java.lang.String Contents) {
		set("Contents", Contents);
	}

	public java.lang.String getContents() {
		return get("Contents");
	}

	public void setUserId(java.lang.Integer UserId) {
		set("UserId", UserId);
	}

	public java.lang.Integer getUserId() {
		return get("UserId");
	}

	public void setFriendId(java.lang.Integer FriendId) {
		set("FriendId", FriendId);
	}

	public java.lang.Integer getFriendId() {
		return get("FriendId");
	}

	public void setEnclosure(java.lang.String Enclosure) {
		set("Enclosure", Enclosure);
	}

	public java.lang.String getEnclosure() {
		return get("Enclosure");
	}

	public void setCreateDate(java.util.Date CreateDate) {
		set("CreateDate", CreateDate);
	}

	public java.util.Date getCreateDate() {
		return get("CreateDate");
	}

}
