package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZAdApplyDays<M extends BaseZAdApplyDays<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setAdApplyId(java.lang.Integer adApplyId) {
		set("ad_apply_id", adApplyId);
	}

	public java.lang.Integer getAdApplyId() {
		return get("ad_apply_id");
	}

	public void setDay(java.sql.Date day) {
		set("day", day);
	}

	public java.sql.Date getDay() {
		return get("day");
	}

}
