package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWaiterOpeOrder<M extends BaseWaiterOpeOrder<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer Id) {
		set("Id", Id);
	}

	public java.lang.Integer getId() {
		return get("Id");
	}

	public void setWaiterId(java.lang.Integer WaiterId) {
		set("WaiterId", WaiterId);
	}

	public java.lang.Integer getWaiterId() {
		return get("WaiterId");
	}

	public void setOrderdId(java.lang.Integer OrderdId) {
		set("OrderdId", OrderdId);
	}

	public java.lang.Integer getOrderdId() {
		return get("OrderdId");
	}

}
