package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrientationSet<M extends BaseOrientationSet<M>> extends Model<M> implements IBean {

	public void setOrientationId(java.lang.Integer orientationId) {
		set("Orientation_id", orientationId);
	}

	public java.lang.Integer getOrientationId() {
		return get("Orientation_id");
	}

	public void setOrientationName(java.lang.String orientationName) {
		set("Orientation_Name", orientationName);
	}

	public java.lang.String getOrientationName() {
		return get("Orientation_Name");
	}

}
