package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTalkaboutTable<M extends BaseTalkaboutTable<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer Id) {
		set("Id", Id);
	}

	public java.lang.Integer getId() {
		return get("Id");
	}

	public void setUserId(java.lang.Integer UserId) {
		set("UserId", UserId);
	}

	public java.lang.Integer getUserId() {
		return get("UserId");
	}

	public void setContents(java.lang.String Contents) {
		set("Contents", Contents);
	}

	public java.lang.String getContents() {
		return get("Contents");
	}

	public void setLongitude(java.lang.Double Longitude) {
		set("Longitude", Longitude);
	}

	public java.lang.Double getLongitude() {
		return get("Longitude");
	}

	public void setLatitude(java.lang.Double Latitude) {
		set("Latitude", Latitude);
	}

	public java.lang.Double getLatitude() {
		return get("Latitude");
	}

	public void setZambia(java.lang.Integer Zambia) {
		set("Zambia", Zambia);
	}

	public java.lang.Integer getZambia() {
		return get("Zambia");
	}

	public void setRange(java.lang.String Range) {
		set("Range", Range);
	}

	public java.lang.String getRange() {
		return get("Range");
	}

	public void setCreateDate(java.util.Date CreateDate) {
		set("CreateDate", CreateDate);
	}

	public java.util.Date getCreateDate() {
		return get("CreateDate");
	}

	public void setReleaseAddress(java.lang.String ReleaseAddress) {
		set("ReleaseAddress", ReleaseAddress);
	}

	public java.lang.String getReleaseAddress() {
		return get("ReleaseAddress");
	}

}
