package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIBackgroundType<M extends BaseIBackgroundType<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer Id) {
		set("Id", Id);
	}

	public java.lang.Integer getId() {
		return get("Id");
	}

	public void setBackgroundType(java.lang.Integer BackgroundType) {
		set("BackgroundType", BackgroundType);
	}

	public java.lang.Integer getBackgroundType() {
		return get("BackgroundType");
	}

	public void setBackground(java.lang.String Background) {
		set("Background", Background);
	}

	public java.lang.String getBackground() {
		return get("Background");
	}

	public void setState(java.lang.Integer State) {
		set("State", State);
	}

	public java.lang.Integer getState() {
		return get("State");
	}

	public void setCreateDate(java.util.Date CreateDate) {
		set("CreateDate", CreateDate);
	}

	public java.util.Date getCreateDate() {
		return get("CreateDate");
	}

}
