package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseShopPingProductOrderDetailsSet<M extends BaseShopPingProductOrderDetailsSet<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer Id) {
		set("Id", Id);
	}

	public java.lang.Integer getId() {
		return get("Id");
	}

	public void setShoppingwallproductorderId(java.lang.Integer shoppingwallproductorderId) {
		set("ShopPingWallProductOrder_Id", shoppingwallproductorderId);
	}

	public java.lang.Integer getShoppingwallproductorderId() {
		return get("ShopPingWallProductOrder_Id");
	}

	public void setShoppingwallproductId(java.lang.Integer shoppingwallproductId) {
		set("ShopPingWallProduct_Id", shoppingwallproductId);
	}

	public java.lang.Integer getShoppingwallproductId() {
		return get("ShopPingWallProduct_Id");
	}

	public void setRemarks(java.lang.String Remarks) {
		set("Remarks", Remarks);
	}

	public java.lang.String getRemarks() {
		return get("Remarks");
	}

	public void setCount(java.lang.Integer Count) {
		set("Count", Count);
	}

	public java.lang.Integer getCount() {
		return get("Count");
	}

	public void setPrice(java.lang.Double Price) {
		set("Price", Price);
	}

	public java.lang.Double getPrice() {
		return get("Price");
	}

	public void setShopColour(java.lang.String ShopColour) {
		set("ShopColour", ShopColour);
	}

	public java.lang.String getShopColour() {
		return get("ShopColour");
	}

	public void setShopSpecifications(java.lang.String ShopSpecifications) {
		set("ShopSpecifications", ShopSpecifications);
	}

	public java.lang.String getShopSpecifications() {
		return get("ShopSpecifications");
	}

}
