package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseHotelSet<M extends BaseHotelSet<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setHotelID(java.lang.String HotelID) {
		set("HotelID", HotelID);
	}

	public java.lang.String getHotelID() {
		return get("HotelID");
	}

	public void setPhoto(java.lang.String Photo) {
		set("Photo", Photo);
	}

	public java.lang.String getPhoto() {
		return get("Photo");
	}

	public void setHotelTypeId(java.lang.Integer HotelTypeId) {
		set("HotelTypeId", HotelTypeId);
	}

	public java.lang.Integer getHotelTypeId() {
		return get("HotelTypeId");
	}

	public void setBedId(java.lang.Integer BedId) {
		set("BedId", BedId);
	}

	public java.lang.Integer getBedId() {
		return get("BedId");
	}

	public void setPrices(java.lang.String Prices) {
		set("Prices", Prices);
	}

	public java.lang.String getPrices() {
		return get("Prices");
	}

	public void setDiscountprice(java.lang.String Discountprice) {
		set("Discountprice", Discountprice);
	}

	public java.lang.String getDiscountprice() {
		return get("Discountprice");
	}

	public void setDeposit(java.lang.String Deposit) {
		set("Deposit", Deposit);
	}

	public java.lang.String getDeposit() {
		return get("Deposit");
	}

	public void setIntroduce(java.lang.String Introduce) {
		set("Introduce", Introduce);
	}

	public java.lang.String getIntroduce() {
		return get("Introduce");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("Store_id", storeId);
	}

	public java.lang.Integer getStoreId() {
		return get("Store_id");
	}

	public void setOrientation(java.lang.Integer Orientation) {
		set("Orientation", Orientation);
	}

	public java.lang.Integer getOrientation() {
		return get("Orientation");
	}

	public void setEquipment(java.lang.String Equipment) {
		set("Equipment", Equipment);
	}

	public java.lang.String getEquipment() {
		return get("Equipment");
	}

}
