package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZcUsertrajectory<M extends BaseZcUsertrajectory<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer Id) {
		set("Id", Id);
	}

	public java.lang.Integer getId() {
		return get("Id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("User_Id", userId);
	}

	public java.lang.Integer getUserId() {
		return get("User_Id");
	}

	public void setLongitude(java.lang.Double Longitude) {
		set("Longitude", Longitude);
	}

	public java.lang.Double getLongitude() {
		return get("Longitude");
	}

	public void setLatitude(java.lang.Double Latitude) {
		set("Latitude", Latitude);
	}

	public java.lang.Double getLatitude() {
		return get("Latitude");
	}

	public void setAddNumId(java.lang.Integer AddNumId) {
		set("AddNumId", AddNumId);
	}

	public java.lang.Integer getAddNumId() {
		return get("AddNumId");
	}

	public void setEntrytime(java.util.Date Entrytime) {
		set("Entrytime", Entrytime);
	}

	public java.util.Date getEntrytime() {
		return get("Entrytime");
	}

	public void setAddress(java.lang.String Address) {
		set("Address", Address);
	}

	public java.lang.String getAddress() {
		return get("Address");
	}

}
