package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZMasterScope<M extends BaseZMasterScope<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public void setScope(java.lang.Integer scope) {
		set("scope", scope);
	}

	public java.lang.Integer getScope() {
		return get("scope");
	}

	public void setProvince(java.lang.Integer province) {
		set("province", province);
	}

	public java.lang.Integer getProvince() {
		return get("province");
	}

	public void setCity(java.lang.Integer city) {
		set("city", city);
	}

	public java.lang.Integer getCity() {
		return get("city");
	}

	public void setCounty(java.lang.Integer county) {
		set("county", county);
	}

	public java.lang.Integer getCounty() {
		return get("county");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setCreateTime(java.sql.Date createTime) {
		set("create_time", createTime);
	}

	public java.sql.Date getCreateTime() {
		return get("create_time");
	}

}
