package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStoreProductValueSet<M extends BaseStoreProductValueSet<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer Id) {
		set("Id", Id);
	}

	public java.lang.Integer getId() {
		return get("Id");
	}

	public void setValue(java.lang.String Value) {
		set("Value", Value);
	}

	public java.lang.String getValue() {
		return get("Value");
	}

	public void setStoreproductpropertyId(java.lang.Integer storeproductpropertyId) {
		set("StoreProductProperty_Id", storeproductpropertyId);
	}

	public java.lang.Integer getStoreproductpropertyId() {
		return get("StoreProductProperty_Id");
	}

	public void setProductId(java.lang.Integer productId) {
		set("Product_Id", productId);
	}

	public java.lang.Integer getProductId() {
		return get("Product_Id");
	}

}
