package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLuckyBuy<M extends BaseLuckyBuy<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer Id) {
		set("Id", Id);
	}

	public java.lang.Integer getId() {
		return get("Id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("Store_Id", storeId);
	}

	public java.lang.Integer getStoreId() {
		return get("Store_Id");
	}

	public void setShopproductId(java.lang.Integer shopproductId) {
		set("ShopProduct_Id", shopproductId);
	}

	public java.lang.Integer getShopproductId() {
		return get("ShopProduct_Id");
	}

	public void setNumber(java.lang.Integer Number) {
		set("Number", Number);
	}

	public java.lang.Integer getNumber() {
		return get("Number");
	}

	public void setUnitPrice(java.lang.Double UnitPrice) {
		set("UnitPrice", UnitPrice);
	}

	public java.lang.Double getUnitPrice() {
		return get("UnitPrice");
	}

	public void setSumPrice(java.lang.Double SumPrice) {
		set("SumPrice", SumPrice);
	}

	public java.lang.Double getSumPrice() {
		return get("SumPrice");
	}

	public void setState(java.lang.String State) {
		set("State", State);
	}

	public java.lang.String getState() {
		return get("State");
	}

	public void setRemarks(java.lang.String Remarks) {
		set("Remarks", Remarks);
	}

	public java.lang.String getRemarks() {
		return get("Remarks");
	}

	public void setPlaceOrderTime(java.util.Date PlaceOrderTime) {
		set("PlaceOrderTime", PlaceOrderTime);
	}

	public java.util.Date getPlaceOrderTime() {
		return get("PlaceOrderTime");
	}

	public void setArriveTime(java.util.Date ArriveTime) {
		set("ArriveTime", ArriveTime);
	}

	public java.util.Date getArriveTime() {
		return get("ArriveTime");
	}

}
