package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSecretTable<M extends BaseSecretTable<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer Id) {
		set("Id", Id);
	}

	public java.lang.Integer getId() {
		return get("Id");
	}

	public void setUserId(java.lang.Integer UserId) {
		set("UserId", UserId);
	}

	public java.lang.Integer getUserId() {
		return get("UserId");
	}

	public void setFriendId(java.lang.Integer FriendId) {
		set("FriendId", FriendId);
	}

	public java.lang.Integer getFriendId() {
		return get("FriendId");
	}

	public void setPassword(java.lang.String Password) {
		set("Password", Password);
	}

	public java.lang.String getPassword() {
		return get("Password");
	}

}
