package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseHotelOrderDetails<M extends BaseHotelOrderDetails<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer Id) {
		set("Id", Id);
	}

	public java.lang.Integer getId() {
		return get("Id");
	}

	public void setOrderId(java.lang.Integer orderId) {
		set("Order_Id", orderId);
	}

	public java.lang.Integer getOrderId() {
		return get("Order_Id");
	}

	public void setProductId(java.lang.Integer productId) {
		set("Product_Id", productId);
	}

	public java.lang.Integer getProductId() {
		return get("Product_Id");
	}

	public void setRemarks(java.lang.String Remarks) {
		set("Remarks", Remarks);
	}

	public java.lang.String getRemarks() {
		return get("Remarks");
	}

	public void setCount(java.lang.Integer Count) {
		set("Count", Count);
	}

	public java.lang.Integer getCount() {
		return get("Count");
	}

	public void setPrice(java.lang.Double Price) {
		set("Price", Price);
	}

	public java.lang.Double getPrice() {
		return get("Price");
	}

	public void setLiveTime(java.util.Date LiveTime) {
		set("LiveTime", LiveTime);
	}

	public java.util.Date getLiveTime() {
		return get("LiveTime");
	}

	public void setArriveTime(java.util.Date ArriveTime) {
		set("ArriveTime", ArriveTime);
	}

	public java.util.Date getArriveTime() {
		return get("ArriveTime");
	}

	public void setOutTime(java.util.Date OutTime) {
		set("OutTime", OutTime);
	}

	public java.util.Date getOutTime() {
		return get("OutTime");
	}

	public void setLiveName(java.lang.String LiveName) {
		set("LiveName", LiveName);
	}

	public java.lang.String getLiveName() {
		return get("LiveName");
	}

	public void setLivePhone(java.lang.String LivePhone) {
		set("LivePhone", LivePhone);
	}

	public java.lang.String getLivePhone() {
		return get("LivePhone");
	}

}
