package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserTypeCenterTableSet<M extends BaseUserTypeCenterTableSet<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer Id) {
		set("Id", Id);
	}

	public java.lang.Integer getId() {
		return get("Id");
	}

	public void setUserid(java.lang.String Userid) {
		set("Userid", Userid);
	}

	public java.lang.String getUserid() {
		return get("Userid");
	}

	public void setUsertypeid(java.lang.String Usertypeid) {
		set("Usertypeid", Usertypeid);
	}

	public java.lang.String getUsertypeid() {
		return get("Usertypeid");
	}

}
