package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRoomFacilities<M extends BaseRoomFacilities<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setRoomId(java.lang.Integer roomId) {
		set("roomId", roomId);
	}

	public java.lang.Integer getRoomId() {
		return get("roomId");
	}

	public void setFName(java.lang.String FName) {
		set("FName", FName);
	}

	public java.lang.String getFName() {
		return get("FName");
	}

	public void setValue(java.lang.Integer Value) {
		set("Value", Value);
	}

	public java.lang.Integer getValue() {
		return get("Value");
	}

}
