package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRegion<M extends BaseRegion<M>> extends Model<M> implements IBean {

	public void setRegionId(java.lang.Integer regionId) {
		set("REGION_ID", regionId);
	}

	public java.lang.Integer getRegionId() {
		return get("REGION_ID");
	}

	public void setRegionCode(java.lang.String regionCode) {
		set("REGION_CODE", regionCode);
	}

	public java.lang.String getRegionCode() {
		return get("REGION_CODE");
	}

	public void setRegionName(java.lang.String regionName) {
		set("REGION_NAME", regionName);
	}

	public java.lang.String getRegionName() {
		return get("REGION_NAME");
	}

	public void setParentId(java.lang.Integer parentId) {
		set("PARENT_ID", parentId);
	}

	public java.lang.Integer getParentId() {
		return get("PARENT_ID");
	}

	public void setRegionLevel(java.lang.Integer regionLevel) {
		set("REGION_LEVEL", regionLevel);
	}

	public java.lang.Integer getRegionLevel() {
		return get("REGION_LEVEL");
	}

	public void setRegionOrder(java.lang.Integer regionOrder) {
		set("REGION_ORDER", regionOrder);
	}

	public java.lang.Integer getRegionOrder() {
		return get("REGION_ORDER");
	}

	public void setRegionNameEn(java.lang.String regionNameEn) {
		set("REGION_NAME_EN", regionNameEn);
	}

	public java.lang.String getRegionNameEn() {
		return get("REGION_NAME_EN");
	}

	public void setRegionShortnameEn(java.lang.String regionShortnameEn) {
		set("REGION_SHORTNAME_EN", regionShortnameEn);
	}

	public java.lang.String getRegionShortnameEn() {
		return get("REGION_SHORTNAME_EN");
	}

}
