package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGroupingTable<M extends BaseGroupingTable<M>> extends Model<M> implements IBean {

	public void setGroupingId(java.lang.Integer GroupingId) {
		set("GroupingId", GroupingId);
	}

	public java.lang.Integer getGroupingId() {
		return get("GroupingId");
	}

	public void setUserId(java.lang.Integer UserId) {
		set("UserId", UserId);
	}

	public java.lang.Integer getUserId() {
		return get("UserId");
	}

	public void setGroupingName(java.lang.String GroupingName) {
		set("GroupingName", GroupingName);
	}

	public java.lang.String getGroupingName() {
		return get("GroupingName");
	}

	public void setPid(java.lang.Integer Pid) {
		set("Pid", Pid);
	}

	public java.lang.Integer getPid() {
		return get("Pid");
	}

	public void setState(java.lang.Integer State) {
		set("State", State);
	}

	public java.lang.Integer getState() {
		return get("State");
	}

}
