package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCrowdTable<M extends BaseCrowdTable<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer Id) {
		set("Id", Id);
	}

	public java.lang.Integer getId() {
		return get("Id");
	}

	public void setUserId(java.lang.Integer UserId) {
		set("UserId", UserId);
	}

	public java.lang.Integer getUserId() {
		return get("UserId");
	}

	public void setCrowdName(java.lang.String CrowdName) {
		set("CrowdName", CrowdName);
	}

	public java.lang.String getCrowdName() {
		return get("CrowdName");
	}

	public void setCrowdNumber(java.lang.String CrowdNumber) {
		set("CrowdNumber", CrowdNumber);
	}

	public java.lang.String getCrowdNumber() {
		return get("CrowdNumber");
	}

	public void setCreateDate(java.util.Date CreateDate) {
		set("CreateDate", CreateDate);
	}

	public java.util.Date getCreateDate() {
		return get("CreateDate");
	}

	public void setRemarks(java.lang.String Remarks) {
		set("Remarks", Remarks);
	}

	public java.lang.String getRemarks() {
		return get("Remarks");
	}

	public void setState(java.lang.String State) {
		set("State", State);
	}

	public java.lang.String getState() {
		return get("State");
	}

}
