package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseShoppingwallproductDetails<M extends BaseShoppingwallproductDetails<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer Id) {
		set("Id", Id);
	}

	public java.lang.Integer getId() {
		return get("Id");
	}

	public void setShopColour(java.lang.String ShopColour) {
		set("ShopColour", ShopColour);
	}

	public java.lang.String getShopColour() {
		return get("ShopColour");
	}

	public void setShoppingwalloproductId(java.lang.Integer shoppingwalloproductId) {
		set("Shoppingwalloproduct_Id", shoppingwalloproductId);
	}

	public java.lang.Integer getShoppingwalloproductId() {
		return get("Shoppingwalloproduct_Id");
	}

	public void setShopSpecifications(java.lang.String ShopSpecifications) {
		set("ShopSpecifications", ShopSpecifications);
	}

	public java.lang.String getShopSpecifications() {
		return get("ShopSpecifications");
	}

}
