package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBusinessHoursSet<M extends BaseBusinessHoursSet<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer Id) {
		set("Id", Id);
	}

	public java.lang.Integer getId() {
		return get("Id");
	}

	public void setStartTime(java.lang.String StartTime) {
		set("StartTime", StartTime);
	}

	public java.lang.String getStartTime() {
		return get("StartTime");
	}

	public void setEndTime(java.lang.String EndTime) {
		set("EndTime", EndTime);
	}

	public java.lang.String getEndTime() {
		return get("EndTime");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("Store_id", storeId);
	}

	public java.lang.Integer getStoreId() {
		return get("Store_id");
	}

}
