package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTableToUser<M extends BaseTableToUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer Id) {
		set("Id", Id);
	}

	public java.lang.Integer getId() {
		return get("Id");
	}

	public void setTableNoId(java.lang.Integer tableNoId) {
		set("tableNoId", tableNoId);
	}

	public java.lang.Integer getTableNoId() {
		return get("tableNoId");
	}

	public void setUserId(java.lang.Integer UserId) {
		set("UserId", UserId);
	}

	public java.lang.Integer getUserId() {
		return get("UserId");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}

	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public void setFlag(java.lang.Integer flag) {
		set("flag", flag);
	}

	public java.lang.Integer getFlag() {
		return get("flag");
	}

	public void setClearTime(java.util.Date ClearTime) {
		set("ClearTime", ClearTime);
	}

	public java.util.Date getClearTime() {
		return get("ClearTime");
	}

	public void setRemake(java.lang.String remake) {
		set("remake", remake);
	}

	public java.lang.String getRemake() {
		return get("remake");
	}

	public void setYDID(java.lang.Integer YDID) {
		set("YDID", YDID);
	}

	public java.lang.Integer getYDID() {
		return get("YDID");
	}

}
