package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAppVersion<M extends BaseAppVersion<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer Id) {
		set("Id", Id);
	}

	public java.lang.Integer getId() {
		return get("Id");
	}

	public void setAppUrl(java.lang.String appUrl) {
		set("appUrl", appUrl);
	}

	public java.lang.String getAppUrl() {
		return get("appUrl");
	}

	public void setAppVersion(java.lang.String appVersion) {
		set("appVersion", appVersion);
	}

	public java.lang.String getAppVersion() {
		return get("appVersion");
	}

	public void setAppDescribe(java.lang.String appDescribe) {
		set("appDescribe", appDescribe);
	}

	public java.lang.String getAppDescribe() {
		return get("appDescribe");
	}

}
