package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZCrowdZhanghao<M extends BaseZCrowdZhanghao<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setPass(java.lang.Integer pass) {
		set("pass", pass);
	}

	public java.lang.Integer getPass() {
		return get("pass");
	}

	public void setCreateTime(java.sql.Date createTime) {
		set("create_time", createTime);
	}

	public java.sql.Date getCreateTime() {
		return get("create_time");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setOwner(java.lang.String owner) {
		set("owner", owner);
	}

	public java.lang.String getOwner() {
		return get("owner");
	}

	public void setCardnum(java.lang.String cardnum) {
		set("cardnum", cardnum);
	}

	public java.lang.String getCardnum() {
		return get("cardnum");
	}

	public void setBank(java.lang.String bank) {
		set("bank", bank);
	}

	public java.lang.String getBank() {
		return get("bank");
	}

	public void setBindtel(java.lang.String bindtel) {
		set("bindtel", bindtel);
	}

	public java.lang.String getBindtel() {
		return get("bindtel");
	}

	public void setCrowdId(java.lang.Integer crowdId) {
		set("crowd_id", crowdId);
	}

	public java.lang.Integer getCrowdId() {
		return get("crowd_id");
	}

}
