package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZcAdditional<M extends BaseZcAdditional<M>> extends Model<M> implements IBean {

	public void setAdditionalid(java.lang.Integer Additionalid) {
		set("Additionalid", Additionalid);
	}

	public java.lang.Integer getAdditionalid() {
		return get("Additionalid");
	}

	public void setAdditionalName(java.lang.String AdditionalName) {
		set("AdditionalName", AdditionalName);
	}

	public java.lang.String getAdditionalName() {
		return get("AdditionalName");
	}

	public void setPid(java.lang.Integer Pid) {
		set("Pid", Pid);
	}

	public java.lang.Integer getPid() {
		return get("Pid");
	}

}
