package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZAdApply<M extends BaseZAdApply<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setImg(java.lang.String img) {
		set("img", img);
	}

	public java.lang.String getImg() {
		return get("img");
	}

	public void setImgcontext(java.lang.String imgcontext) {
		set("imgcontext", imgcontext);
	}

	public java.lang.String getImgcontext() {
		return get("imgcontext");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setCreateTime(java.sql.Date createTime) {
		set("create_time", createTime);
	}

	public java.sql.Date getCreateTime() {
		return get("create_time");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("store_id", storeId);
	}

	public java.lang.Integer getStoreId() {
		return get("store_id");
	}

	public void setLocation(java.lang.String location) {
		set("location", location);
	}

	public java.lang.String getLocation() {
		return get("location");
	}

	public void setProvinceId(java.lang.Integer provinceId) {
		set("province_id", provinceId);
	}

	public java.lang.Integer getProvinceId() {
		return get("province_id");
	}

	public void setCityId(java.lang.Integer cityId) {
		set("city_id", cityId);
	}

	public java.lang.Integer getCityId() {
		return get("city_id");
	}

	public void setCountyId(java.lang.Integer countyId) {
		set("county_id", countyId);
	}

	public java.lang.Integer getCountyId() {
		return get("county_id");
	}

	public void setShowtype(java.lang.Integer showtype) {
		set("showtype", showtype);
	}

	public java.lang.Integer getShowtype() {
		return get("showtype");
	}

	public void setPass(java.lang.Integer pass) {
		set("pass", pass);
	}

	public java.lang.Integer getPass() {
		return get("pass");
	}

	public void setPayType(java.lang.Integer payType) {
		set("payType", payType);
	}

	public java.lang.Integer getPayType() {
		return get("payType");
	}

	public void setMoney(java.math.BigDecimal money) {
		set("money", money);
	}

	public java.math.BigDecimal getMoney() {
		return get("money");
	}

	public void setOrderId(java.lang.String orderId) {
		set("order_id", orderId);
	}

	public java.lang.String getOrderId() {
		return get("order_id");
	}

	public void setThirdId(java.lang.String thirdId) {
		set("third_id", thirdId);
	}

	public java.lang.String getThirdId() {
		return get("third_id");
	}

	public void setFinishTime(java.sql.Date finishTime) {
		set("finish_time", finishTime);
	}

	public java.sql.Date getFinishTime() {
		return get("finish_time");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

}
