package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZNoticeBaoming<M extends BaseZNoticeBaoming<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setMainImg(java.lang.String mainImg) {
		set("main_img", mainImg);
	}

	public java.lang.String getMainImg() {
		return get("main_img");
	}

	public void setShowincontent(java.lang.Integer showincontent) {
		set("showincontent", showincontent);
	}

	public java.lang.Integer getShowincontent() {
		return get("showincontent");
	}

	public void setProvinceId(java.lang.Integer provinceId) {
		set("province_id", provinceId);
	}

	public java.lang.Integer getProvinceId() {
		return get("province_id");
	}

	public void setCityId(java.lang.Integer cityId) {
		set("city_id", cityId);
	}

	public java.lang.Integer getCityId() {
		return get("city_id");
	}

	public void setCountyId(java.lang.Integer countyId) {
		set("county_id", countyId);
	}

	public java.lang.Integer getCountyId() {
		return get("county_id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setGetbaoming(java.lang.Integer getbaoming) {
		set("getbaoming", getbaoming);
	}

	public java.lang.Integer getGetbaoming() {
		return get("getbaoming");
	}

	public void setGetjingfei(java.lang.Integer getjingfei) {
		set("getjingfei", getjingfei);
	}

	public java.lang.Integer getGetjingfei() {
		return get("getjingfei");
	}

	public void setBaomingfei(java.math.BigDecimal baomingfei) {
		set("baomingfei", baomingfei);
	}

	public java.math.BigDecimal getBaomingfei() {
		return get("baomingfei");
	}

	public void setJingfei(java.math.BigDecimal jingfei) {
		set("jingfei", jingfei);
	}

	public java.math.BigDecimal getJingfei() {
		return get("jingfei");
	}

	public void setBStarttime(java.sql.Date bStarttime) {
		set("b_starttime", bStarttime);
	}

	public java.sql.Date getBStarttime() {
		return get("b_starttime");
	}

	public void setBEndtime(java.sql.Date bEndtime) {
		set("b_endtime", bEndtime);
	}

	public java.sql.Date getBEndtime() {
		return get("b_endtime");
	}

	public void setStarttime(java.sql.Date starttime) {
		set("starttime", starttime);
	}

	public java.sql.Date getStarttime() {
		return get("starttime");
	}

	public void setEndtime(java.sql.Date endtime) {
		set("endtime", endtime);
	}

	public java.sql.Date getEndtime() {
		return get("endtime");
	}

	public void setIssex(java.lang.Integer issex) {
		set("issex", issex);
	}

	public java.lang.Integer getIssex() {
		return get("issex");
	}

	public void setNums(java.lang.Integer nums) {
		set("nums", nums);
	}

	public java.lang.Integer getNums() {
		return get("nums");
	}

	public void setCreateTime(java.sql.Date createTime) {
		set("create_time", createTime);
	}

	public java.sql.Date getCreateTime() {
		return get("create_time");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setLocationX(java.lang.String locationX) {
		set("location_x", locationX);
	}

	public java.lang.String getLocationX() {
		return get("location_x");
	}

	public void setLocationY(java.lang.String locationY) {
		set("location_y", locationY);
	}

	public java.lang.String getLocationY() {
		return get("location_y");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public void setMannums(java.lang.Integer mannums) {
		set("mannums", mannums);
	}

	public java.lang.Integer getMannums() {
		return get("mannums");
	}

	public void setWomanums(java.lang.Integer womanums) {
		set("womanums", womanums);
	}

	public java.lang.Integer getWomanums() {
		return get("womanums");
	}

}
