package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProductPropertySet<M extends BaseProductPropertySet<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer Id) {
		set("Id", Id);
	}

	public java.lang.Integer getId() {
		return get("Id");
	}

	public void setName(java.lang.String Name) {
		set("Name", Name);
	}

	public java.lang.String getName() {
		return get("Name");
	}

	public void setProducttypeId(java.lang.Integer producttypeId) {
		set("ProductType_Id", producttypeId);
	}

	public java.lang.Integer getProducttypeId() {
		return get("ProductType_Id");
	}

	public void setDistinguish(java.lang.Integer Distinguish) {
		set("Distinguish", Distinguish);
	}

	public java.lang.Integer getDistinguish() {
		return get("Distinguish");
	}

}
