package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTakeAwayApply<M extends BaseTakeAwayApply<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("storeId", storeId);
	}

	public java.lang.Integer getStoreId() {
		return get("storeId");
	}

	public void setApplyTime(java.util.Date applyTime) {
		set("applyTime", applyTime);
	}

	public java.util.Date getApplyTime() {
		return get("applyTime");
	}

	public void setApplyLength(java.lang.String applyLength) {
		set("applyLength", applyLength);
	}

	public java.lang.String getApplyLength() {
		return get("applyLength");
	}

	public void setOvertime(java.util.Date overtime) {
		set("overtime", overtime);
	}

	public java.util.Date getOvertime() {
		return get("overtime");
	}

	public void setFlag(java.lang.Integer flag) {
		set("flag", flag);
	}

	public java.lang.Integer getFlag() {
		return get("flag");
	}

}
