package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTableMenuSet<M extends BaseTableMenuSet<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer Id) {
		set("Id", Id);
	}

	public java.lang.Integer getId() {
		return get("Id");
	}

	public void setReservationid(java.lang.Integer Reservationid) {
		set("Reservationid", Reservationid);
	}

	public java.lang.Integer getReservationid() {
		return get("Reservationid");
	}

	public void setProductid(java.lang.Integer productid) {
		set("productid", productid);
	}

	public java.lang.Integer getProductid() {
		return get("productid");
	}

	public void setProductcount(java.lang.Integer productcount) {
		set("productcount", productcount);
	}

	public java.lang.Integer getProductcount() {
		return get("productcount");
	}

	public void setState(java.lang.Integer state) {
		set("state", state);
	}

	public java.lang.Integer getState() {
		return get("state");
	}

	public void setDeletes(java.lang.Integer Deletes) {
		set("Deletes", Deletes);
	}

	public java.lang.Integer getDeletes() {
		return get("Deletes");
	}

	public void setRemarks(java.lang.String Remarks) {
		set("Remarks", Remarks);
	}

	public java.lang.String getRemarks() {
		return get("Remarks");
	}

	public void setTime(java.util.Date Time) {
		set("Time", Time);
	}

	public java.util.Date getTime() {
		return get("Time");
	}

}
