package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOnlineMessage<M extends BaseOnlineMessage<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer Id) {
		set("Id", Id);
	}

	public java.lang.Integer getId() {
		return get("Id");
	}

	public void setFromUserId(java.lang.Integer FromUserId) {
		set("FromUserId", FromUserId);
	}

	public java.lang.Integer getFromUserId() {
		return get("FromUserId");
	}

	public void setFromStoreId(java.lang.Integer FromStoreId) {
		set("FromStoreId", FromStoreId);
	}

	public java.lang.Integer getFromStoreId() {
		return get("FromStoreId");
	}

	public void setToUserId(java.lang.Integer ToUserId) {
		set("ToUserId", ToUserId);
	}

	public java.lang.Integer getToUserId() {
		return get("ToUserId");
	}

	public void setToStoreId(java.lang.Integer ToStoreId) {
		set("ToStoreId", ToStoreId);
	}

	public java.lang.Integer getToStoreId() {
		return get("ToStoreId");
	}

	public void setMessage(java.lang.String Message) {
		set("Message", Message);
	}

	public java.lang.String getMessage() {
		return get("Message");
	}

	public void setMessageImg(java.lang.String MessageImg) {
		set("MessageImg", MessageImg);
	}

	public java.lang.String getMessageImg() {
		return get("MessageImg");
	}

	public void setTypes(java.lang.Integer types) {
		set("types", types);
	}

	public java.lang.Integer getTypes() {
		return get("types");
	}

	public void setIsRead(java.lang.Integer isRead) {
		set("isRead", isRead);
	}

	public java.lang.Integer getIsRead() {
		return get("isRead");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}

	public java.util.Date getCreatetime() {
		return get("createtime");
	}

}
