package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZMasterP<M extends BaseZMasterP<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setMasterId(java.lang.Integer masterId) {
		set("master_id", masterId);
	}

	public java.lang.Integer getMasterId() {
		return get("master_id");
	}

	public void setMoney(java.lang.Integer money) {
		set("money", money);
	}

	public java.lang.Integer getMoney() {
		return get("money");
	}

	public void setAd(java.lang.Integer ad) {
		set("ad", ad);
	}

	public java.lang.Integer getAd() {
		return get("ad");
	}

	public void setReport(java.lang.Integer report) {
		set("report", report);
	}

	public java.lang.Integer getReport() {
		return get("report");
	}

	public void setMessage(java.lang.Integer message) {
		set("message", message);
	}

	public java.lang.Integer getMessage() {
		return get("message");
	}

	public void setMaster(java.lang.Integer master) {
		set("master", master);
	}

	public java.lang.Integer getMaster() {
		return get("master");
	}

}
