package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrderListDetails<M extends BaseOrderListDetails<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setOrderId(java.lang.Integer orderId) {
		set("orderId", orderId);
	}

	public java.lang.Integer getOrderId() {
		return get("orderId");
	}

	public void setProductId(java.lang.Integer ProductId) {
		set("ProductId", ProductId);
	}

	public java.lang.Integer getProductId() {
		return get("ProductId");
	}

	public void setProductName(java.lang.String ProductName) {
		set("ProductName", ProductName);
	}

	public java.lang.String getProductName() {
		return get("ProductName");
	}

	public void setPrice(java.lang.Double price) {
		set("price", price);
	}

	public java.lang.Double getPrice() {
		return get("price");
	}

	public void setNum(java.lang.Integer num) {
		set("num", num);
	}

	public java.lang.Integer getNum() {
		return get("num");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("storeId", storeId);
	}

	public java.lang.Integer getStoreId() {
		return get("storeId");
	}

	public void setStoreName(java.lang.String storeName) {
		set("storeName", storeName);
	}

	public java.lang.String getStoreName() {
		return get("storeName");
	}

	public void setRemake(java.lang.String remake) {
		set("remake", remake);
	}

	public java.lang.String getRemake() {
		return get("remake");
	}

	public void setIsTable(java.lang.Integer isTable) {
		set("isTable", isTable);
	}

	public java.lang.Integer getIsTable() {
		return get("isTable");
	}

	public void setCookflag(java.lang.Integer cookflag) {
		set("cookflag", cookflag);
	}

	public java.lang.Integer getCookflag() {
		return get("cookflag");
	}

}
