package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZPhonemsm<M extends BaseZPhonemsm<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setTelephone(java.lang.String telephone) {
		set("telephone", telephone);
	}

	public java.lang.String getTelephone() {
		return get("telephone");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setIdentifyCode(java.lang.String identifyCode) {
		set("identifyCode", identifyCode);
	}

	public java.lang.String getIdentifyCode() {
		return get("identifyCode");
	}

	public void setSendStatus(java.lang.Integer sendStatus) {
		set("sendStatus", sendStatus);
	}

	public java.lang.Integer getSendStatus() {
		return get("sendStatus");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setCreateTime(java.sql.Date createTime) {
		set("createTime", createTime);
	}

	public java.sql.Date getCreateTime() {
		return get("createTime");
	}

}
