package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTableNumbersSet<M extends BaseTableNumbersSet<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer Id) {
		set("Id", Id);
	}

	public java.lang.Integer getId() {
		return get("Id");
	}

	public void setTableNumbersName(java.lang.String TableNumbersName) {
		set("TableNumbersName", TableNumbersName);
	}

	public java.lang.String getTableNumbersName() {
		return get("TableNumbersName");
	}

}
