package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePrinterConfig<M extends BasePrinterConfig<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer Id) {
		set("Id", Id);
	}

	public java.lang.Integer getId() {
		return get("Id");
	}

	public void setPrintsCoding(java.lang.String PrintsCoding) {
		set("PrintsCoding", PrintsCoding);
	}

	public java.lang.String getPrintsCoding() {
		return get("PrintsCoding");
	}

	public void setKeys(java.lang.String Keys) {
		set("Keys", Keys);
	}

	public java.lang.String getKeys() {
		return get("Keys");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("Store_Id", storeId);
	}

	public java.lang.Integer getStoreId() {
		return get("Store_Id");
	}

	public void setPrintType(java.lang.String PrintType) {
		set("PrintType", PrintType);
	}

	public java.lang.String getPrintType() {
		return get("PrintType");
	}

}
