package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMessageList<M extends BaseMessageList<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer Id) {
		set("Id", Id);
	}

	public java.lang.Integer getId() {
		return get("Id");
	}

	public void setFromUserId(java.lang.Integer FromUserId) {
		set("FromUserId", FromUserId);
	}

	public java.lang.Integer getFromUserId() {
		return get("FromUserId");
	}

	public void setFromStoreId(java.lang.Integer FromStoreId) {
		set("FromStoreId", FromStoreId);
	}

	public java.lang.Integer getFromStoreId() {
		return get("FromStoreId");
	}

	public void setToUserId(java.lang.Integer toUserId) {
		set("toUserId", toUserId);
	}

	public java.lang.Integer getToUserId() {
		return get("toUserId");
	}

	public void setToStoreId(java.lang.Integer toStoreId) {
		set("toStoreId", toStoreId);
	}

	public java.lang.Integer getToStoreId() {
		return get("toStoreId");
	}

	public void setLastTime(java.util.Date lastTime) {
		set("lastTime", lastTime);
	}

	public java.util.Date getLastTime() {
		return get("lastTime");
	}

	public void setLastMessage(java.lang.String lastMessage) {
		set("lastMessage", lastMessage);
	}

	public java.lang.String getLastMessage() {
		return get("lastMessage");
	}

}
