package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZcGoodsandcar<M extends BaseZcGoodsandcar<M>> extends Model<M> implements IBean {

	public void setGoodsAndCarid(java.lang.Integer GoodsAndCarid) {
		set("GoodsAndCarid", GoodsAndCarid);
	}

	public java.lang.Integer getGoodsAndCarid() {
		return get("GoodsAndCarid");
	}

	public void setPicture(java.lang.String picture) {
		set("picture", picture);
	}

	public java.lang.String getPicture() {
		return get("picture");
	}

	public void setStartingPoint(java.lang.String StartingPoint) {
		set("StartingPoint", StartingPoint);
	}

	public java.lang.String getStartingPoint() {
		return get("StartingPoint");
	}

	public void setArriving(java.lang.String Arriving) {
		set("Arriving", Arriving);
	}

	public java.lang.String getArriving() {
		return get("Arriving");
	}

	public void setDeparturetime(java.util.Date Departuretime) {
		set("Departuretime", Departuretime);
	}

	public java.util.Date getDeparturetime() {
		return get("Departuretime");
	}

	public void setAdditional(java.lang.String Additional) {
		set("Additional", Additional);
	}

	public java.lang.String getAdditional() {
		return get("Additional");
	}

	public void setJizou(java.lang.Integer Jizou) {
		set("Jizou", Jizou);
	}

	public java.lang.Integer getJizou() {
		return get("Jizou");
	}

	public void setGoodsName(java.lang.String GoodsName) {
		set("GoodsName", GoodsName);
	}

	public java.lang.String getGoodsName() {
		return get("GoodsName");
	}

	public void setGoodsType(java.lang.String GoodsType) {
		set("GoodsType", GoodsType);
	}

	public java.lang.String getGoodsType() {
		return get("GoodsType");
	}

	public void setWeight(java.lang.String Weight) {
		set("Weight", Weight);
	}

	public java.lang.String getWeight() {
		return get("Weight");
	}

	public void setVolume(java.lang.String Volume) {
		set("Volume", Volume);
	}

	public java.lang.String getVolume() {
		return get("Volume");
	}

	public void setThenumber(java.lang.Integer Thenumber) {
		set("Thenumber", Thenumber);
	}

	public java.lang.Integer getThenumber() {
		return get("Thenumber");
	}

	public void setContacts(java.lang.String Contacts) {
		set("Contacts", Contacts);
	}

	public java.lang.String getContacts() {
		return get("Contacts");
	}

	public void setTelephone(java.lang.String Telephone) {
		set("Telephone", Telephone);
	}

	public java.lang.String getTelephone() {
		return get("Telephone");
	}

	public void setPostscript(java.lang.String Postscript) {
		set("Postscript", Postscript);
	}

	public java.lang.String getPostscript() {
		return get("Postscript");
	}

	public void setReleasetime(java.lang.String Releasetime) {
		set("Releasetime", Releasetime);
	}

	public java.lang.String getReleasetime() {
		return get("Releasetime");
	}

}
