package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTUser<M extends BaseTUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}

	public java.lang.Integer getUserId() {
		return get("userId");
	}

	public void setUserImg(java.lang.String userImg) {
		set("userImg", userImg);
	}

	public java.lang.String getUserImg() {
		return get("userImg");
	}

	public void setUserName(java.lang.String userName) {
		set("userName", userName);
	}

	public java.lang.String getUserName() {
		return get("userName");
	}

	public void setUserPwd(java.lang.String userPwd) {
		set("userPwd", userPwd);
	}

	public java.lang.String getUserPwd() {
		return get("userPwd");
	}

	public void setUserNameCN(java.lang.String userNameCN) {
		set("userNameCN", userNameCN);
	}

	public java.lang.String getUserNameCN() {
		return get("userNameCN");
	}

	public void setUserTel(java.lang.String userTel) {
		set("userTel", userTel);
	}

	public java.lang.String getUserTel() {
		return get("userTel");
	}

	public void setFWArea(java.lang.String FWArea) {
		set("FWArea", FWArea);
	}

	public java.lang.String getFWArea() {
		return get("FWArea");
	}

	public void setPNo(java.lang.String PNo) {
		set("PNo", PNo);
	}

	public java.lang.String getPNo() {
		return get("PNo");
	}

	public void setCNo(java.lang.String CNo) {
		set("CNo", CNo);
	}

	public java.lang.String getCNo() {
		return get("CNo");
	}

	public void setANo(java.lang.String ANo) {
		set("ANo", ANo);
	}

	public java.lang.String getANo() {
		return get("ANo");
	}

	public void setTMoney(java.lang.Double TMoney) {
		set("TMoney", TMoney);
	}

	public java.lang.Double getTMoney() {
		return get("TMoney");
	}

	public void setFlag(java.lang.Integer flag) {
		set("flag", flag);
	}

	public java.lang.Integer getFlag() {
		return get("flag");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}

	public java.util.Date getCreatetime() {
		return get("createtime");
	}

}
