package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZNoticeFankui<M extends BaseZNoticeFankui<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setMainImg(java.lang.String mainImg) {
		set("main_img", mainImg);
	}

	public java.lang.String getMainImg() {
		return get("main_img");
	}

	public void setShownickname(java.lang.Integer shownickname) {
		set("shownickname", shownickname);
	}

	public java.lang.Integer getShownickname() {
		return get("shownickname");
	}

	public void setProvinceId(java.lang.Integer provinceId) {
		set("province_id", provinceId);
	}

	public java.lang.Integer getProvinceId() {
		return get("province_id");
	}

	public void setCityId(java.lang.Integer cityId) {
		set("city_id", cityId);
	}

	public java.lang.Integer getCityId() {
		return get("city_id");
	}

	public void setCountyId(java.lang.Integer countyId) {
		set("county_id", countyId);
	}

	public java.lang.Integer getCountyId() {
		return get("county_id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setCreateTime(java.sql.Date createTime) {
		set("create_time", createTime);
	}

	public java.sql.Date getCreateTime() {
		return get("create_time");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setLocationX(java.lang.String locationX) {
		set("location_x", locationX);
	}

	public java.lang.String getLocationX() {
		return get("location_x");
	}

	public void setLocationY(java.lang.String locationY) {
		set("location_y", locationY);
	}

	public java.lang.String getLocationY() {
		return get("location_y");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public void setShowincontent(java.lang.Integer showincontent) {
		set("showincontent", showincontent);
	}

	public java.lang.Integer getShowincontent() {
		return get("showincontent");
	}

	public void setPass(java.lang.Integer pass) {
		set("pass", pass);
	}

	public java.lang.Integer getPass() {
		return get("pass");
	}

	public void setPraisenum(java.lang.Integer praisenum) {
		set("praisenum", praisenum);
	}

	public java.lang.Integer getPraisenum() {
		return get("praisenum");
	}

}
