package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWaiterMessagList<M extends BaseWaiterMessagList<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setTableNo(java.lang.String tableNo) {
		set("tableNo", tableNo);
	}

	public java.lang.String getTableNo() {
		return get("tableNo");
	}

	public void setToWaiterId(java.lang.Integer toWaiterId) {
		set("toWaiterId", toWaiterId);
	}

	public java.lang.Integer getToWaiterId() {
		return get("toWaiterId");
	}

	public void setFlag(java.lang.Integer flag) {
		set("flag", flag);
	}

	public java.lang.Integer getFlag() {
		return get("flag");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}

	public java.util.Date getCreatetime() {
		return get("createtime");
	}

}
