package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZcTaxi<M extends BaseZcTaxi<M>> extends Model<M> implements IBean {

	public void setTaxiid(java.lang.Integer Taxiid) {
		set("Taxiid", Taxiid);
	}

	public java.lang.Integer getTaxiid() {
		return get("Taxiid");
	}

	public void setTheOwner(java.lang.String TheOwner) {
		set("TheOwner", TheOwner);
	}

	public java.lang.String getTheOwner() {
		return get("TheOwner");
	}

	public void setID(java.lang.String ID) {
		set("ID", ID);
	}

	public java.lang.String getID() {
		return get("ID");
	}

	public void setLicenseplate(java.lang.String Licenseplate) {
		set("Licenseplate", Licenseplate);
	}

	public java.lang.String getLicenseplate() {
		return get("Licenseplate");
	}

	public void setIDPhotojust(java.lang.String IDPhotojust) {
		set("IDPhotojust", IDPhotojust);
	}

	public java.lang.String getIDPhotojust() {
		return get("IDPhotojust");
	}

	public void setIDPhotoback(java.lang.String IDPhotoback) {
		set("IDPhotoback", IDPhotoback);
	}

	public java.lang.String getIDPhotoback() {
		return get("IDPhotoback");
	}

	public void setDrivinglicense(java.lang.String Drivinglicense) {
		set("Drivinglicense", Drivinglicense);
	}

	public java.lang.String getDrivinglicense() {
		return get("Drivinglicense");
	}

	public void setCarPhoto(java.lang.String CarPhoto) {
		set("CarPhoto", CarPhoto);
	}

	public java.lang.String getCarPhoto() {
		return get("CarPhoto");
	}

	public void setDriverName(java.lang.String DriverName) {
		set("DriverName", DriverName);
	}

	public java.lang.String getDriverName() {
		return get("DriverName");
	}

	public void setAge(java.lang.Integer Age) {
		set("Age", Age);
	}

	public java.lang.Integer getAge() {
		return get("Age");
	}

	public void setIntroduce(java.lang.String Introduce) {
		set("Introduce", Introduce);
	}

	public java.lang.String getIntroduce() {
		return get("Introduce");
	}

	public void setState(java.lang.Integer state) {
		set("state", state);
	}

	public java.lang.Integer getState() {
		return get("state");
	}

}
