package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseReservationOrderSet<M extends BaseReservationOrderSet<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer Id) {
		set("Id", Id);
	}

	public java.lang.Integer getId() {
		return get("Id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("User_Id", userId);
	}

	public java.lang.Integer getUserId() {
		return get("User_Id");
	}

	public void setReservationId(java.lang.Integer reservationId) {
		set("Reservation_Id", reservationId);
	}

	public java.lang.Integer getReservationId() {
		return get("Reservation_Id");
	}

	public void setCurrentTime(java.util.Date CurrentTime) {
		set("CurrentTime", CurrentTime);
	}

	public java.util.Date getCurrentTime() {
		return get("CurrentTime");
	}

	public void setMoney(java.lang.Double Money) {
		set("Money", Money);
	}

	public java.lang.Double getMoney() {
		return get("Money");
	}

	public void setReservationCount(java.lang.Integer ReservationCount) {
		set("ReservationCount", ReservationCount);
	}

	public java.lang.Integer getReservationCount() {
		return get("ReservationCount");
	}

	public void setRemarks(java.lang.String Remarks) {
		set("Remarks", Remarks);
	}

	public java.lang.String getRemarks() {
		return get("Remarks");
	}

	public void setIsDotDish(java.lang.Boolean IsDotDish) {
		set("IsDotDish", IsDotDish);
	}

	public java.lang.Boolean getIsDotDish() {
		return get("IsDotDish");
	}

	public void setReservationTime(java.util.Date ReservationTime) {
		set("ReservationTime", ReservationTime);
	}

	public java.util.Date getReservationTime() {
		return get("ReservationTime");
	}

	public void setState(java.lang.Integer State) {
		set("State", State);
	}

	public java.lang.Integer getState() {
		return get("State");
	}

	public void setSumPrice(java.lang.Double SumPrice) {
		set("SumPrice", SumPrice);
	}

	public java.lang.Double getSumPrice() {
		return get("SumPrice");
	}

	public void setWaiterTable(java.lang.String WaiterTable) {
		set("WaiterTable", WaiterTable);
	}

	public java.lang.String getWaiterTable() {
		return get("WaiterTable");
	}

	public void setInIsDelete(java.lang.Integer InIsDelete) {
		set("InIsDelete", InIsDelete);
	}

	public java.lang.Integer getInIsDelete() {
		return get("InIsDelete");
	}

}
