package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePraiseTable<M extends BasePraiseTable<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer Id) {
		set("Id", Id);
	}

	public java.lang.Integer getId() {
		return get("Id");
	}

	public void setUserId(java.lang.Integer UserId) {
		set("UserId", UserId);
	}

	public java.lang.Integer getUserId() {
		return get("UserId");
	}

	public void setTalkId(java.lang.Integer TalkId) {
		set("TalkId", TalkId);
	}

	public java.lang.Integer getTalkId() {
		return get("TalkId");
	}

	public void setState(java.lang.Integer State) {
		set("State", State);
	}

	public java.lang.Integer getState() {
		return get("State");
	}

}
