package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCookTableSet<M extends BaseCookTableSet<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer Id) {
		set("Id", Id);
	}

	public java.lang.Integer getId() {
		return get("Id");
	}

	public void setUserid(java.lang.String Userid) {
		set("Userid", Userid);
	}

	public java.lang.String getUserid() {
		return get("Userid");
	}

	public void setStoreid(java.lang.String Storeid) {
		set("Storeid", Storeid);
	}

	public java.lang.String getStoreid() {
		return get("Storeid");
	}

	public void setDescriptio(java.lang.String Descriptio) {
		set("Descriptio", Descriptio);
	}

	public java.lang.String getDescriptio() {
		return get("Descriptio");
	}

	public void setCookState(java.lang.String CookState) {
		set("CookState", CookState);
	}

	public java.lang.String getCookState() {
		return get("CookState");
	}

	public void setCreateTime(java.lang.String CreateTime) {
		set("CreateTime", CreateTime);
	}

	public java.lang.String getCreateTime() {
		return get("CreateTime");
	}

}
