package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZTemporary<M extends BaseZTemporary<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setUserid(java.lang.Integer userid) {
		set("userid", userid);
	}

	public java.lang.Integer getUserid() {
		return get("userid");
	}

	public void setPhone(java.lang.String Phone) {
		set("Phone", Phone);
	}

	public java.lang.String getPhone() {
		return get("Phone");
	}

	public void setPID(java.lang.Integer PID) {
		set("PID", PID);
	}

	public java.lang.Integer getPID() {
		return get("PID");
	}

}
