package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePrintList<M extends BasePrintList<M>> extends Model<M> implements IBean {

	public void setPrintId(java.lang.Integer PrintId) {
		set("PrintId", PrintId);
	}

	public java.lang.Integer getPrintId() {
		return get("PrintId");
	}

	public void setPrintSN(java.lang.String PrintSN) {
		set("PrintSN", PrintSN);
	}

	public java.lang.String getPrintSN() {
		return get("PrintSN");
	}

	public void setPrintSKEY(java.lang.String PrintSKEY) {
		set("PrintSKEY", PrintSKEY);
	}

	public java.lang.String getPrintSKEY() {
		return get("PrintSKEY");
	}

	public void setPrintName(java.lang.String PrintName) {
		set("PrintName", PrintName);
	}

	public java.lang.String getPrintName() {
		return get("PrintName");
	}

	public void setPrintTel(java.lang.String PrintTel) {
		set("PrintTel", PrintTel);
	}

	public java.lang.String getPrintTel() {
		return get("PrintTel");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("storeId", storeId);
	}

	public java.lang.Integer getStoreId() {
		return get("storeId");
	}

}
