package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZcTaxidriver<M extends BaseZcTaxidriver<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setPhoto(java.lang.String Photo) {
		set("Photo", Photo);
	}

	public java.lang.String getPhoto() {
		return get("Photo");
	}

	public void setUserId(java.lang.Integer userId) {
		set("User_id", userId);
	}

	public java.lang.Integer getUserId() {
		return get("User_id");
	}

	public void setDriverLicense(java.lang.String DriverLicense) {
		set("DriverLicense", DriverLicense);
	}

	public java.lang.String getDriverLicense() {
		return get("DriverLicense");
	}

	public void setDrivingLicense(java.lang.String DrivingLicense) {
		set("DrivingLicense", DrivingLicense);
	}

	public java.lang.String getDrivingLicense() {
		return get("DrivingLicense");
	}

	public void setCompanyId(java.lang.Integer companyId) {
		set("Company_Id", companyId);
	}

	public java.lang.Integer getCompanyId() {
		return get("Company_Id");
	}

	public void setDriverState(java.lang.Integer DriverState) {
		set("DriverState", DriverState);
	}

	public java.lang.Integer getDriverState() {
		return get("DriverState");
	}

	public void setVehicleId(java.lang.Integer vehicleId) {
		set("Vehicle_Id", vehicleId);
	}

	public java.lang.Integer getVehicleId() {
		return get("Vehicle_Id");
	}

	public void setLongitude(java.lang.String Longitude) {
		set("Longitude", Longitude);
	}

	public java.lang.String getLongitude() {
		return get("Longitude");
	}

	public void setLatitude(java.lang.String Latitude) {
		set("Latitude", Latitude);
	}

	public java.lang.String getLatitude() {
		return get("Latitude");
	}

	public void setTime(java.util.Date Time) {
		set("Time", Time);
	}

	public java.util.Date getTime() {
		return get("Time");
	}

}
