package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTableNoSet<M extends BaseTableNoSet<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer Id) {
		set("Id", Id);
	}

	public java.lang.Integer getId() {
		return get("Id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("storeId", storeId);
	}

	public java.lang.Integer getStoreId() {
		return get("storeId");
	}

	public void setTableNo(java.lang.String tableNo) {
		set("tableNo", tableNo);
	}

	public java.lang.String getTableNo() {
		return get("tableNo");
	}

	public void setFlag(java.lang.Integer flag) {
		set("flag", flag);
	}

	public java.lang.Integer getFlag() {
		return get("flag");
	}

	public void setTableId(java.lang.Integer TableId) {
		set("TableId", TableId);
	}

	public java.lang.Integer getTableId() {
		return get("TableId");
	}

	public void setQRurl(java.lang.String QRurl) {
		set("QRurl", QRurl);
	}

	public java.lang.String getQRurl() {
		return get("QRurl");
	}

}
