package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGrabOrder<M extends BaseGrabOrder<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setTUID(java.lang.Integer TUID) {
		set("TUID", TUID);
	}

	public java.lang.Integer getTUID() {
		return get("TUID");
	}

	public void setOrderId(java.lang.Integer OrderId) {
		set("OrderId", OrderId);
	}

	public java.lang.Integer getOrderId() {
		return get("OrderId");
	}

	public void setGrabTime(java.util.Date GrabTime) {
		set("GrabTime", GrabTime);
	}

	public java.util.Date getGrabTime() {
		return get("GrabTime");
	}

	public void setOrderAmont(java.lang.Double OrderAmont) {
		set("OrderAmont", OrderAmont);
	}

	public java.lang.Double getOrderAmont() {
		return get("OrderAmont");
	}

	public void setGrabMoney(java.lang.Double GrabMoney) {
		set("GrabMoney", GrabMoney);
	}

	public java.lang.Double getGrabMoney() {
		return get("GrabMoney");
	}

	public void setFlag(java.lang.Integer flag) {
		set("flag", flag);
	}

	public java.lang.Integer getFlag() {
		return get("flag");
	}

	public void setFinishTime(java.util.Date finishTime) {
		set("finishTime", finishTime);
	}

	public java.util.Date getFinishTime() {
		return get("finishTime");
	}

}
