package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePrintDishes<M extends BasePrintDishes<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer Id) {
		set("Id", Id);
	}

	public java.lang.Integer getId() {
		return get("Id");
	}

	public void setPrintId(java.lang.Integer PrintId) {
		set("PrintId", PrintId);
	}

	public java.lang.Integer getPrintId() {
		return get("PrintId");
	}

	public void setDishesId(java.lang.Integer DishesId) {
		set("DishesId", DishesId);
	}

	public java.lang.Integer getDishesId() {
		return get("DishesId");
	}

}
