package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSelectTableList<M extends BaseSelectTableList<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer Id) {
		set("Id", Id);
	}

	public java.lang.Integer getId() {
		return get("Id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}

	public java.lang.Integer getUserId() {
		return get("userId");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("storeId", storeId);
	}

	public java.lang.Integer getStoreId() {
		return get("storeId");
	}

	public void setReservationId(java.lang.Integer ReservationId) {
		set("ReservationId", ReservationId);
	}

	public java.lang.Integer getReservationId() {
		return get("ReservationId");
	}

	public void setTypeName(java.lang.String TypeName) {
		set("TypeName", TypeName);
	}

	public java.lang.String getTypeName() {
		return get("TypeName");
	}

	public void setNumberRrange(java.lang.String NumberRrange) {
		set("NumberRrange", NumberRrange);
	}

	public java.lang.String getNumberRrange() {
		return get("NumberRrange");
	}

	public void setTheDate(java.util.Date theDate) {
		set("theDate", theDate);
	}

	public java.util.Date getTheDate() {
		return get("theDate");
	}

	public void setStime(java.lang.String Stime) {
		set("Stime", Stime);
	}

	public java.lang.String getStime() {
		return get("Stime");
	}

	public void setEtime(java.lang.String Etime) {
		set("Etime", Etime);
	}

	public java.lang.String getEtime() {
		return get("Etime");
	}

	public void setTheMoney(java.lang.Double theMoney) {
		set("theMoney", theMoney);
	}

	public java.lang.Double getTheMoney() {
		return get("theMoney");
	}

	public void setTableNo(java.lang.String tableNo) {
		set("tableNo", tableNo);
	}

	public java.lang.String getTableNo() {
		return get("tableNo");
	}

	public void setNum(java.lang.Integer num) {
		set("num", num);
	}

	public java.lang.Integer getNum() {
		return get("num");
	}

	public void setPrice(java.lang.Double price) {
		set("price", price);
	}

	public java.lang.Double getPrice() {
		return get("price");
	}

	public void setFlag(java.lang.Integer flag) {
		set("flag", flag);
	}

	public java.lang.Integer getFlag() {
		return get("flag");
	}

	public void setTableNoId(java.lang.Integer TableNoId) {
		set("TableNoId", TableNoId);
	}

	public java.lang.Integer getTableNoId() {
		return get("TableNoId");
	}

}
