package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZAd<M extends BaseZAd<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setStartday(java.sql.Date startday) {
		set("startday", startday);
	}

	public java.sql.Date getStartday() {
		return get("startday");
	}

	public void setEndday(java.sql.Date endday) {
		set("endday", endday);
	}

	public java.sql.Date getEndday() {
		return get("endday");
	}

	public void setFirst(java.math.BigDecimal first) {
		set("first", first);
	}

	public java.math.BigDecimal getFirst() {
		return get("first");
	}

	public void setSecond(java.math.BigDecimal second) {
		set("second", second);
	}

	public java.math.BigDecimal getSecond() {
		return get("second");
	}

	public void setThird(java.math.BigDecimal third) {
		set("third", third);
	}

	public java.math.BigDecimal getThird() {
		return get("third");
	}

	public void setFourth(java.math.BigDecimal fourth) {
		set("fourth", fourth);
	}

	public java.math.BigDecimal getFourth() {
		return get("fourth");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setCreateTime(java.sql.Date createTime) {
		set("create_time", createTime);
	}

	public java.sql.Date getCreateTime() {
		return get("create_time");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

}
