package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserAuth<M extends BaseUserAuth<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer Id) {
		set("Id", Id);
	}

	public java.lang.Integer getId() {
		return get("Id");
	}

	public void setUserId(java.lang.Integer UserId) {
		set("UserId", UserId);
	}

	public java.lang.Integer getUserId() {
		return get("UserId");
	}

	public void setIDPhotoZ(java.lang.String IDPhotoZ) {
		set("IDPhotoZ", IDPhotoZ);
	}

	public java.lang.String getIDPhotoZ() {
		return get("IDPhotoZ");
	}

	public void setIDPhotoF(java.lang.String IDPhotoF) {
		set("IDPhotoF", IDPhotoF);
	}

	public java.lang.String getIDPhotoF() {
		return get("IDPhotoF");
	}

	public void setIncunabulum(java.lang.String incunabulum) {
		set("incunabulum", incunabulum);
	}

	public java.lang.String getIncunabulum() {
		return get("incunabulum");
	}

	public void setRealname(java.lang.String Realname) {
		set("Realname", Realname);
	}

	public java.lang.String getRealname() {
		return get("Realname");
	}

	public void setState(java.lang.Integer State) {
		set("State", State);
	}

	public java.lang.Integer getState() {
		return get("State");
	}

	public void setCreateDate(java.util.Date CreateDate) {
		set("CreateDate", CreateDate);
	}

	public java.util.Date getCreateDate() {
		return get("CreateDate");
	}

}
