package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTableSet<M extends BaseTableSet<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer Id) {
		set("Id", Id);
	}

	public java.lang.Integer getId() {
		return get("Id");
	}

	public void setQRCode(java.lang.String QRCode) {
		set("QRCode", QRCode);
	}

	public java.lang.String getQRCode() {
		return get("QRCode");
	}

	public void setTableStateid(java.lang.Integer TableStateid) {
		set("TableStateid", TableStateid);
	}

	public java.lang.Integer getTableStateid() {
		return get("TableStateid");
	}

	public void setTableNumbersid(java.lang.Integer TableNumbersid) {
		set("TableNumbersid", TableNumbersid);
	}

	public java.lang.Integer getTableNumbersid() {
		return get("TableNumbersid");
	}

	public void setStoreid(java.lang.Integer Storeid) {
		set("Storeid", Storeid);
	}

	public java.lang.Integer getStoreid() {
		return get("Storeid");
	}

	public void setInTime(java.util.Date inTime) {
		set("inTime", inTime);
	}

	public java.util.Date getInTime() {
		return get("inTime");
	}

}
