package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZMarry<M extends BaseZMarry<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setNickname(java.lang.String nickname) {
		set("nickname", nickname);
	}

	public java.lang.String getNickname() {
		return get("nickname");
	}

	public void setHunyingguan(java.lang.String hunyingguan) {
		set("hunyingguan", hunyingguan);
	}

	public java.lang.String getHunyingguan() {
		return get("hunyingguan");
	}

	public void setSex(java.lang.Integer sex) {
		set("sex", sex);
	}

	public java.lang.Integer getSex() {
		return get("sex");
	}

	public void setAge(java.lang.Integer age) {
		set("age", age);
	}

	public java.lang.Integer getAge() {
		return get("age");
	}

	public void setHigh(java.lang.Integer high) {
		set("high", high);
	}

	public java.lang.Integer getHigh() {
		return get("high");
	}

	public void setWeight(java.lang.Integer weight) {
		set("weight", weight);
	}

	public java.lang.Integer getWeight() {
		return get("weight");
	}

	public void setDegrees(java.lang.String degrees) {
		set("degrees", degrees);
	}

	public java.lang.String getDegrees() {
		return get("degrees");
	}

	public void setFaith(java.lang.String faith) {
		set("faith", faith);
	}

	public java.lang.String getFaith() {
		return get("faith");
	}

	public void setJob(java.lang.String job) {
		set("job", job);
	}

	public java.lang.String getJob() {
		return get("job");
	}

	public void setPosition(java.lang.String position) {
		set("position", position);
	}

	public java.lang.String getPosition() {
		return get("position");
	}

	public void setIsmarried(java.lang.Integer ismarried) {
		set("ismarried", ismarried);
	}

	public java.lang.Integer getIsmarried() {
		return get("ismarried");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public void setIncome(java.lang.Integer income) {
		set("income", income);
	}

	public java.lang.Integer getIncome() {
		return get("income");
	}

	public void setHouse(java.lang.Integer house) {
		set("house", house);
	}

	public java.lang.Integer getHouse() {
		return get("house");
	}

	public void setCar(java.lang.Integer car) {
		set("car", car);
	}

	public java.lang.Integer getCar() {
		return get("car");
	}

	public void setSmoke(java.lang.Integer smoke) {
		set("smoke", smoke);
	}

	public java.lang.Integer getSmoke() {
		return get("smoke");
	}

	public void setDrink(java.lang.Integer drink) {
		set("drink", drink);
	}

	public java.lang.Integer getDrink() {
		return get("drink");
	}

	public void setHoppy(java.lang.String hoppy) {
		set("hoppy", hoppy);
	}

	public java.lang.String getHoppy() {
		return get("hoppy");
	}

	public void setRequirements(java.lang.String requirements) {
		set("requirements", requirements);
	}

	public java.lang.String getRequirements() {
		return get("requirements");
	}

	public void setSign (java.lang.String sign ) {
		set("sign ", sign );
	}

	public java.lang.String getSign () {
		return get("sign ");
	}

	public void setCreatetime(java.sql.Date createtime) {
		set("createtime", createtime);
	}

	public java.sql.Date getCreatetime() {
		return get("createtime");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public void setBackimg(java.lang.String backimg) {
		set("backimg", backimg);
	}

	public java.lang.String getBackimg() {
		return get("backimg");
	}

	public void setImgs(java.lang.String imgs) {
		set("imgs", imgs);
	}

	public java.lang.String getImgs() {
		return get("imgs");
	}

	public void setCityId(java.lang.Integer cityId) {
		set("city_id", cityId);
	}

	public java.lang.Integer getCityId() {
		return get("city_id");
	}

	public void setCountyId(java.lang.Integer countyId) {
		set("county_id", countyId);
	}

	public java.lang.Integer getCountyId() {
		return get("county_id");
	}

	public void setLocationX(java.lang.String locationX) {
		set("location_x", locationX);
	}

	public java.lang.String getLocationX() {
		return get("location_x");
	}

	public void setLocationY(java.lang.String locationY) {
		set("location_y", locationY);
	}

	public java.lang.String getLocationY() {
		return get("location_y");
	}

	public void setPass(java.lang.Integer pass) {
		set("pass", pass);
	}

	public java.lang.Integer getPass() {
		return get("pass");
	}

	public void setTruename(java.lang.String truename) {
		set("truename", truename);
	}

	public java.lang.String getTruename() {
		return get("truename");
	}

	public void setBirthaddress(java.lang.String birthaddress) {
		set("birthaddress", birthaddress);
	}

	public java.lang.String getBirthaddress() {
		return get("birthaddress");
	}

	public void setStayaddress(java.lang.String stayaddress) {
		set("stayaddress", stayaddress);
	}

	public java.lang.String getStayaddress() {
		return get("stayaddress");
	}

	public void setIdcard(java.lang.String idcard) {
		set("idcard", idcard);
	}

	public java.lang.String getIdcard() {
		return get("idcard");
	}

	public void setIdimgs(java.lang.String idimgs) {
		set("idimgs", idimgs);
	}

	public java.lang.String getIdimgs() {
		return get("idimgs");
	}

	public void setTel(java.lang.String tel) {
		set("tel", tel);
	}

	public java.lang.String getTel() {
		return get("tel");
	}

}
