package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProductSet<M extends BaseProductSet<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer Id) {
		set("Id", Id);
	}

	public java.lang.Integer getId() {
		return get("Id");
	}

	public void setName(java.lang.String Name) {
		set("Name", Name);
	}

	public java.lang.String getName() {
		return get("Name");
	}

	public void setDescription(java.lang.String Description) {
		set("Description", Description);
	}

	public java.lang.String getDescription() {
		return get("Description");
	}

	public void setPhoto(java.lang.String Photo) {
		set("Photo", Photo);
	}

	public java.lang.String getPhoto() {
		return get("Photo");
	}

	public void setPrice(java.lang.String Price) {
		set("Price", Price);
	}

	public java.lang.String getPrice() {
		return get("Price");
	}

	public void setProducttypeId(java.lang.Integer producttypeId) {
		set("ProductType_Id", producttypeId);
	}

	public java.lang.Integer getProducttypeId() {
		return get("ProductType_Id");
	}

	public void setDiyproducttypeId(java.lang.Integer diyproducttypeId) {
		set("DIYProductType_Id", diyproducttypeId);
	}

	public java.lang.Integer getDiyproducttypeId() {
		return get("DIYProductType_Id");
	}

	public void setStoreId(java.lang.Integer storeId) {
		set("Store_Id", storeId);
	}

	public java.lang.Integer getStoreId() {
		return get("Store_Id");
	}

	public void setInTime(java.util.Date inTime) {
		set("inTime", inTime);
	}

	public java.util.Date getInTime() {
		return get("inTime");
	}

	public void setNotice(java.lang.String Notice) {
		set("Notice", Notice);
	}

	public java.lang.String getNotice() {
		return get("Notice");
	}

	public void setCompName(java.lang.String CompName) {
		set("CompName", CompName);
	}

	public java.lang.String getCompName() {
		return get("CompName");
	}

	public void setTel(java.lang.String Tel) {
		set("Tel", Tel);
	}

	public java.lang.String getTel() {
		return get("Tel");
	}

	public void setEmail(java.lang.String Email) {
		set("Email", Email);
	}

	public java.lang.String getEmail() {
		return get("Email");
	}

	public void setHTML(java.lang.String HTML) {
		set("HTML", HTML);
	}

	public java.lang.String getHTML() {
		return get("HTML");
	}

	public void setState(java.lang.String State) {
		set("State", State);
	}

	public java.lang.String getState() {
		return get("State");
	}

	public void setSpecificationTableid(java.lang.Integer SpecificationTableid) {
		set("SpecificationTableid", SpecificationTableid);
	}

	public java.lang.Integer getSpecificationTableid() {
		return get("SpecificationTableid");
	}

	public void setIsHot(java.lang.Integer isHot) {
		set("is_hot", isHot);
	}

	public java.lang.Integer getIsHot() {
		return get("is_hot");
	}

	public void setIsOut(java.lang.Integer isOut) {
		set("isOut", isOut);
	}

	public java.lang.Integer getIsOut() {
		return get("isOut");
	}

	public void setPassMoney(java.lang.Double PassMoney) {
		set("PassMoney", PassMoney);
	}

	public java.lang.Double getPassMoney() {
		return get("PassMoney");
	}

	public void setMarketPrice(java.lang.Double MarketPrice) {
		set("MarketPrice", MarketPrice);
	}

	public java.lang.Double getMarketPrice() {
		return get("MarketPrice");
	}

	public void setIsYJ(java.lang.Integer isYJ) {
		set("isYJ", isYJ);
	}

	public java.lang.Integer getIsYJ() {
		return get("isYJ");
	}

	public void setYjMoney(java.lang.Double YjMoney) {
		set("YjMoney", YjMoney);
	}

	public java.lang.Double getYjMoney() {
		return get("YjMoney");
	}

	public void setProductXQ(java.lang.String ProductXQ) {
		set("ProductXQ", ProductXQ);
	}

	public java.lang.String getProductXQ() {
		return get("ProductXQ");
	}

}
