package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserTypeSet<M extends BaseUserTypeSet<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer Id) {
		set("Id", Id);
	}

	public java.lang.Integer getId() {
		return get("Id");
	}

	public void setUserTypeName(java.lang.String UserTypeName) {
		set("UserTypeName", UserTypeName);
	}

	public java.lang.String getUserTypeName() {
		return get("UserTypeName");
	}

}
