package org.tgcloud.zhanzhang.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZClickInfo<M extends BaseZClickInfo<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setInfoType(java.lang.Integer infoType) {
		set("info_type", infoType);
	}

	public java.lang.Integer getInfoType() {
		return get("info_type");
	}

	public void setCreateTime(java.sql.Date createTime) {
		set("create_time", createTime);
	}

	public java.sql.Date getCreateTime() {
		return get("create_time");
	}

	public void setNums(java.lang.Integer nums) {
		set("nums", nums);
	}

	public java.lang.Integer getNums() {
		return get("nums");
	}

}
