package org.tgcloud.zhanzhang.entity;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("region", "REGION_ID", Region.class);
		arp.addMapping("SUMiddleSet", "id", SUMiddleSet.class);
		arp.addMapping("z_ad", "id", ZAd.class);
		arp.addMapping("z_ad_apply", "id", ZAdApply.class);
		arp.addMapping("z_ad_apply_days", "id", ZAdApplyDays.class);
		arp.addMapping("z_agriculture", "id", ZAgriculture.class);
		arp.addMapping("z_cards", "id", ZCards.class);
		arp.addMapping("z_click_info", "id", ZClickInfo.class);
		arp.addMapping("z_company", "id", ZCompany.class);
		arp.addMapping("z_company_contact", "id", ZCompanyContact.class);
		arp.addMapping("z_company_goods", "id", ZCompanyGoods.class);
		arp.addMapping("z_company_link", "id", ZCompanyLink.class);
		arp.addMapping("z_company_news", "id", ZCompanyNews.class);
		arp.addMapping("z_company_support", "id", ZCompanySupport.class);
		arp.addMapping("z_company_work", "id", ZCompanyWork.class);
		arp.addMapping("z_context_path", "id", ZContextPath.class);
		arp.addMapping("z_crowd", "id", ZCrowd.class);
		arp.addMapping("z_crowd_donate", "id", ZCrowdDonate.class);
		arp.addMapping("z_crowd_hongshizi", "id", ZCrowdHongshizi.class);
		arp.addMapping("Z_crowd_reply", "id", ZCrowdReply.class);
		arp.addMapping("z_crowd_shenfen", "id", ZCrowdShenfen.class);
		arp.addMapping("z_crowd_yiyuan", "id", ZCrowdYiyuan.class);
		arp.addMapping("z_crowd_zhanghao", "id", ZCrowdZhanghao.class);
		arp.addMapping("z_findwork", "id", ZFindwork.class);
		arp.addMapping("z_findwork_place", "id", ZFindworkPlace.class);
		arp.addMapping("z_findworker", "id", ZFindworker.class);
		arp.addMapping("z_img_path", "id", ZImgPath.class);
		arp.addMapping("z_info_url", "id", ZInfoUrl.class);
		arp.addMapping("z_local", "id", ZLocal.class);
		arp.addMapping("z_manager", "id", ZManager.class);
		arp.addMapping("z_marry", "id", ZMarry.class);
		arp.addMapping("z_master", "id", ZMaster.class);
		arp.addMapping("z_master_notice", "id", ZMasterNotice.class);
		arp.addMapping("z_master_p", "id", ZMasterP.class);
		arp.addMapping("z_master_scope", "id", ZMasterScope.class);
		arp.addMapping("z_money_out", "id", ZMoneyOut.class);
		arp.addMapping("z_notice_baoming", "id", ZNoticeBaoming.class);
		arp.addMapping("z_notice_baoming_apply", "id", ZNoticeBaomingApply.class);
		arp.addMapping("z_notice_fankui", "id", ZNoticeFankui.class);
		arp.addMapping("Z_notice_pinglun", "id", ZNoticePinglun.class);
		arp.addMapping("z_notice_praise", "id", ZNoticePraise.class);
		arp.addMapping("z_notice_qiuzheng", "id", ZNoticeQiuzheng.class);
		arp.addMapping("Z_notice_reply", "id", ZNoticeReply.class);
		arp.addMapping("z_notice_tongzhi", "id", ZNoticeTongzhi.class);
		arp.addMapping("z_notice_zhengqiu", "id", ZNoticeZhengqiu.class);
		arp.addMapping("z_pay", "id", ZPay.class);
		arp.addMapping("z_people_need", "id", ZPeopleNeed.class);
		arp.addMapping("z_people_service", "id", ZPeopleService.class);
		arp.addMapping("z_phonemsm", "id", ZPhonemsm.class);
		arp.addMapping("z_praise_info", "id", ZPraiseInfo.class);
		arp.addMapping("z_product", "id", ZProduct.class);
		arp.addMapping("z_product_show", "id", ZProductShow.class);
		arp.addMapping("z_report_info", "id", ZReportInfo.class);
		arp.addMapping("z_search_info", "id", ZSearchInfo.class);
		arp.addMapping("z_store_info", "id", ZStoreInfo.class);
		arp.addMapping("z_travel_guide", "id", ZTravelGuide.class);
		arp.addMapping("z_travel_scenic", "id", ZTravelScenic.class);
		arp.addMapping("z_user", "id", ZUser.class);
		arp.addMapping("z_user_pingbi", "id", ZUserPingbi.class);
		arp.addMapping("z_userclick_info", "id", ZUserclickInfo.class);
	}
}

