package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseAdvertisementTable;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdvertisementTable extends BaseAdvertisementTable<AdvertisementTable> {
	public static final AdvertisementTable dao = new AdvertisementTable();
}
