package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseAppVersion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AppVersion extends BaseAppVersion<AppVersion> {
	public static final AppVersion dao = new AppVersion();
}
