package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseBankCardListT;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BankCardListT extends BaseBankCardListT<BankCardListT> {
	public static final BankCardListT dao = new BankCardListT();
}
