package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseBankCardList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BankCardList extends BaseBankCardList<BankCardList> {
	public static final BankCardList dao = new BankCardList();
}
