package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseBusinessHoursSet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BusinessHoursSet extends BaseBusinessHoursSet<BusinessHoursSet> {
	public static final BusinessHoursSet dao = new BusinessHoursSet();
}
