package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseCollectionTable;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CollectionTable extends BaseCollectionTable<CollectionTable> {
	public static final CollectionTable dao = new CollectionTable();
}
