package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseCommentTypeSet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CommentTypeSet extends BaseCommentTypeSet<CommentTypeSet> {
	public static final CommentTypeSet dao = new CommentTypeSet();
}
