package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseCommentSet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CommentSet extends BaseCommentSet<CommentSet> {
	public static final CommentSet dao = new CommentSet();
}
