package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseCookList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CookList extends BaseCookList<CookList> {
	public static final CookList dao = new CookList();
}
