package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseCookTableSet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CookTableSet extends BaseCookTableSet<CookTableSet> {
	public static final CookTableSet dao = new CookTableSet();
}
