package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseCrowdTable;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrowdTable extends BaseCrowdTable<CrowdTable> {
	public static final CrowdTable dao = new CrowdTable();
}
