package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseCuisineSet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CuisineSet extends BaseCuisineSet<CuisineSet> {
	public static final CuisineSet dao = new CuisineSet();
}
