package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseFriendTable;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FriendTable extends BaseFriendTable<FriendTable> {
	public static final FriendTable dao = new FriendTable();
}
