package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseGrabOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GrabOrder extends BaseGrabOrder<GrabOrder> {
	public static final GrabOrder dao = new GrabOrder();
}
