package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseGroupingTable;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GroupingTable extends BaseGroupingTable<GroupingTable> {
	public static final GroupingTable dao = new GroupingTable();
}
