package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseHotelType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HotelType extends BaseHotelType<HotelType> {
	public static final HotelType dao = new HotelType();
}
