package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseHotelOrderDetails;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HotelOrderDetails extends BaseHotelOrderDetails<HotelOrderDetails> {
	public static final HotelOrderDetails dao = new HotelOrderDetails();
}
