package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseHotelSet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HotelSet extends BaseHotelSet<HotelSet> {
	public static final HotelSet dao = new HotelSet();
}
