package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseIBackgroundType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IBackgroundType extends BaseIBackgroundType<IBackgroundType> {
	public static final IBackgroundType dao = new IBackgroundType();
}
