package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseIdentifyingCode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IdentifyingCode extends BaseIdentifyingCode<IdentifyingCode> {
	public static final IdentifyingCode dao = new IdentifyingCode();
}
