package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseInvitationTable;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class InvitationTable extends BaseInvitationTable<InvitationTable> {
	public static final InvitationTable dao = new InvitationTable();
}
