package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseLuckyBuy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LuckyBuy extends BaseLuckyBuy<LuckyBuy> {
	public static final LuckyBuy dao = new LuckyBuy();
}
