package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseMessageList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MessageList extends BaseMessageList<MessageList> {
	public static final MessageList dao = new MessageList();
}
