package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseOnlineMessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OnlineMessage extends BaseOnlineMessage<OnlineMessage> {
	public static final OnlineMessage dao = new OnlineMessage();
}
