package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseOrderDetailsSet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderDetailsSet extends BaseOrderDetailsSet<OrderDetailsSet> {
	public static final OrderDetailsSet dao = new OrderDetailsSet();
}
