package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseOrderListDetails;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderListDetails extends BaseOrderListDetails<OrderListDetails> {
	public static final OrderListDetails dao = new OrderListDetails();
}
