package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseOrderList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderList extends BaseOrderList<OrderList> {
	public static final OrderList dao = new OrderList();
}
