package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseOrderSet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderSet extends BaseOrderSet<OrderSet> {
	public static final OrderSet dao = new OrderSet();
}
