package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseOrientationSet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrientationSet extends BaseOrientationSet<OrientationSet> {
	public static final OrientationSet dao = new OrientationSet();
}
