package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BasePFoodsave;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PFoodsave extends BasePFoodsave<PFoodsave> {
	public static final PFoodsave dao = new PFoodsave();
}
