package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BasePictureTable;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PictureTable extends BasePictureTable<PictureTable> {
	public static final PictureTable dao = new PictureTable();
}
