package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BasePraiseTable;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PraiseTable extends BasePraiseTable<PraiseTable> {
	public static final PraiseTable dao = new PraiseTable();
}
