package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BasePrintDishes;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PrintDishes extends BasePrintDishes<PrintDishes> {
	public static final PrintDishes dao = new PrintDishes();
}
