package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BasePrintInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PrintInfo extends BasePrintInfo<PrintInfo> {
	public static final PrintInfo dao = new PrintInfo();
}
