package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BasePrintList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PrintList extends BasePrintList<PrintList> {
	public static final PrintList dao = new PrintList();
}
