package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BasePrinterConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PrinterConfig extends BasePrinterConfig<PrinterConfig> {
	public static final PrinterConfig dao = new PrinterConfig();
}
