package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseProductSalesValue;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductSalesValue extends BaseProductSalesValue<ProductSalesValue> {
	public static final ProductSalesValue dao = new ProductSalesValue();
}
