package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseProductInfoList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductInfoList extends BaseProductInfoList<ProductInfoList> {
	public static final ProductInfoList dao = new ProductInfoList();
}
