package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseProductValueSet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductValueSet extends BaseProductValueSet<ProductValueSet> {
	public static final ProductValueSet dao = new ProductValueSet();
}
