package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseProductComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductComment extends BaseProductComment<ProductComment> {
	public static final ProductComment dao = new ProductComment();
}
