package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseProductTypeSet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductTypeSet extends BaseProductTypeSet<ProductTypeSet> {
	public static final ProductTypeSet dao = new ProductTypeSet();
}
