package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseProductPropertySet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductPropertySet extends BaseProductPropertySet<ProductPropertySet> {
	public static final ProductPropertySet dao = new ProductPropertySet();
}
