package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseProductSet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductSet extends BaseProductSet<ProductSet> {
	public static final ProductSet dao = new ProductSet();
}
