package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseProductSpec;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductSpec extends BaseProductSpec<ProductSpec> {
	public static final ProductSpec dao = new ProductSpec();
}
