package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseReservationSet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ReservationSet extends BaseReservationSet<ReservationSet> {
	public static final ReservationSet dao = new ReservationSet();
}
