package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseReservationOrderSet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ReservationOrderSet extends BaseReservationOrderSet<ReservationOrderSet> {
	public static final ReservationOrderSet dao = new ReservationOrderSet();
}
