package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseReserveType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ReserveType extends BaseReserveType<ReserveType> {
	public static final ReserveType dao = new ReserveType();
}
