package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseRoomOrderInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoomOrderInfo extends BaseRoomOrderInfo<RoomOrderInfo> {
	public static final RoomOrderInfo dao = new RoomOrderInfo();
}
