package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseRoomFacilities;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoomFacilities extends BaseRoomFacilities<RoomFacilities> {
	public static final RoomFacilities dao = new RoomFacilities();
}
