package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseSecretTable;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SecretTable extends BaseSecretTable<SecretTable> {
	public static final SecretTable dao = new SecretTable();
}
