package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseSelectTableList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SelectTableList extends BaseSelectTableList<SelectTableList> {
	public static final SelectTableList dao = new SelectTableList();
}
