package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseSelectTableToOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SelectTableToOrder extends BaseSelectTableToOrder<SelectTableToOrder> {
	public static final SelectTableToOrder dao = new SelectTableToOrder();
}
