package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseShopPingCart;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShopPingCart extends BaseShopPingCart<ShopPingCart> {
	public static final ShopPingCart dao = new ShopPingCart();
}
