package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseShopPingProductCommentSet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShopPingProductCommentSet extends BaseShopPingProductCommentSet<ShopPingProductCommentSet> {
	public static final ShopPingProductCommentSet dao = new ShopPingProductCommentSet();
}
