package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseShopPingProductOrderDetailsSet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShopPingProductOrderDetailsSet extends BaseShopPingProductOrderDetailsSet<ShopPingProductOrderDetailsSet> {
	public static final ShopPingProductOrderDetailsSet dao = new ShopPingProductOrderDetailsSet();
}
