package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseShoppingWallTypeProduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShoppingWallTypeProduct extends BaseShoppingWallTypeProduct<ShoppingWallTypeProduct> {
	public static final ShoppingWallTypeProduct dao = new ShoppingWallTypeProduct();
}
