package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseShopPingCartSet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShopPingCartSet extends BaseShopPingCartSet<ShopPingCartSet> {
	public static final ShopPingCartSet dao = new ShopPingCartSet();
}
