package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseShoppingWallProductTypeSet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShoppingWallProductTypeSet extends BaseShoppingWallProductTypeSet<ShoppingWallProductTypeSet> {
	public static final ShoppingWallProductTypeSet dao = new ShoppingWallProductTypeSet();
}
