package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseShopPingProductOrderSet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShopPingProductOrderSet extends BaseShopPingProductOrderSet<ShopPingProductOrderSet> {
	public static final ShopPingProductOrderSet dao = new ShopPingProductOrderSet();
}
