package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseShoppingWallProductSet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShoppingWallProductSet extends BaseShoppingWallProductSet<ShoppingWallProductSet> {
	public static final ShoppingWallProductSet dao = new ShoppingWallProductSet();
}
