package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseShoppingwallproductDetails;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShoppingwallproductDetails extends BaseShoppingwallproductDetails<ShoppingwallproductDetails> {
	public static final ShoppingwallproductDetails dao = new ShoppingwallproductDetails();
}
