package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseSpecificationTableSet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SpecificationTableSet extends BaseSpecificationTableSet<SpecificationTableSet> {
	public static final SpecificationTableSet dao = new SpecificationTableSet();
}
