package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseStoreSet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StoreSet extends BaseStoreSet<StoreSet> {
	public static final StoreSet dao = new StoreSet();
}
