package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseStoreProductTypeSet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StoreProductTypeSet extends BaseStoreProductTypeSet<StoreProductTypeSet> {
	public static final StoreProductTypeSet dao = new StoreProductTypeSet();
}
