package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseStoreValueSet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StoreValueSet extends BaseStoreValueSet<StoreValueSet> {
	public static final StoreValueSet dao = new StoreValueSet();
}
