package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseStoreTypeSet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StoreTypeSet extends BaseStoreTypeSet<StoreTypeSet> {
	public static final StoreTypeSet dao = new StoreTypeSet();
}
