package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseStoreBlackist;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StoreBlackist extends BaseStoreBlackist<StoreBlackist> {
	public static final StoreBlackist dao = new StoreBlackist();
}
