package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseStorePropertySet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StorePropertySet extends BaseStorePropertySet<StorePropertySet> {
	public static final StorePropertySet dao = new StorePropertySet();
}
