package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseStoreHotelty;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StoreHotelty extends BaseStoreHotelty<StoreHotelty> {
	public static final StoreHotelty dao = new StoreHotelty();
}
