package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseStoreProductPropertySet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StoreProductPropertySet extends BaseStoreProductPropertySet<StoreProductPropertySet> {
	public static final StoreProductPropertySet dao = new StoreProductPropertySet();
}
