package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseStoreProductValueSet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StoreProductValueSet extends BaseStoreProductValueSet<StoreProductValueSet> {
	public static final StoreProductValueSet dao = new StoreProductValueSet();
}
