package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseSUMiddleSet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SUMiddleSet extends BaseSUMiddleSet<SUMiddleSet> {
	public static final SUMiddleSet dao = new SUMiddleSet();
}
