package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseTableNumbersSet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TableNumbersSet extends BaseTableNumbersSet<TableNumbersSet> {
	public static final TableNumbersSet dao = new TableNumbersSet();
}
