package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseTableNoSet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TableNoSet extends BaseTableNoSet<TableNoSet> {
	public static final TableNoSet dao = new TableNoSet();
}
