package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseTableState;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TableState extends BaseTableState<TableState> {
	public static final TableState dao = new TableState();
}
