package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseTableMenuSet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TableMenuSet extends BaseTableMenuSet<TableMenuSet> {
	public static final TableMenuSet dao = new TableMenuSet();
}
