package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseTableSet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TableSet extends BaseTableSet<TableSet> {
	public static final TableSet dao = new TableSet();
}
