package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseTableNoToOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TableNoToOrder extends BaseTableNoToOrder<TableNoToOrder> {
	public static final TableNoToOrder dao = new TableNoToOrder();
}
