package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseTableToUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TableToUser extends BaseTableToUser<TableToUser> {
	public static final TableToUser dao = new TableToUser();
}
