package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseTakeAwayApply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TakeAwayApply extends BaseTakeAwayApply<TakeAwayApply> {
	public static final TakeAwayApply dao = new TakeAwayApply();
}
