package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseTalkaboutTable;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TalkaboutTable extends BaseTalkaboutTable<TalkaboutTable> {
	public static final TalkaboutTable dao = new TalkaboutTable();
}
