package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseTemporary;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Temporary extends BaseTemporary<Temporary> {
	public static final Temporary dao = new Temporary();
}
