package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseTLieban;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TLieban extends BaseTLieban<TLieban> {
	public static final TLieban dao = new TLieban();
}
