package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseTScanning;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TScanning extends BaseTScanning<TScanning> {
	public static final TScanning dao = new TScanning();
}
