package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseTTransport;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TTransport extends BaseTTransport<TTransport> {
	public static final TTransport dao = new TTransport();
}
