package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseTUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TUser extends BaseTUser<TUser> {
	public static final TUser dao = new TUser();
}
