package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseUserTypeSet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserTypeSet extends BaseUserTypeSet<UserTypeSet> {
	public static final UserTypeSet dao = new UserTypeSet();
}
