package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseUserAuth;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserAuth extends BaseUserAuth<UserAuth> {
	public static final UserAuth dao = new UserAuth();
}
