package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseUserTypeCenterTableSet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserTypeCenterTableSet extends BaseUserTypeCenterTableSet<UserTypeCenterTableSet> {
	public static final UserTypeCenterTableSet dao = new UserTypeCenterTableSet();
}
