package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseUserDetails;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserDetails extends BaseUserDetails<UserDetails> {
	public static final UserDetails dao = new UserDetails();
}
