package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseUserAlbum;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserAlbum extends BaseUserAlbum<UserAlbum> {
	public static final UserAlbum dao = new UserAlbum();
}
