package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseUserGroupTable;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserGroupTable extends BaseUserGroupTable<UserGroupTable> {
	public static final UserGroupTable dao = new UserGroupTable();
}
