package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseUserAddressSet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserAddressSet extends BaseUserAddressSet<UserAddressSet> {
	public static final UserAddressSet dao = new UserAddressSet();
}
