package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseWaiterList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WaiterList extends BaseWaiterList<WaiterList> {
	public static final WaiterList dao = new WaiterList();
}
