package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseWaiterOpeOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WaiterOpeOrder extends BaseWaiterOpeOrder<WaiterOpeOrder> {
	public static final WaiterOpeOrder dao = new WaiterOpeOrder();
}
