package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseWaiterTable;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WaiterTable extends BaseWaiterTable<WaiterTable> {
	public static final WaiterTable dao = new WaiterTable();
}
