package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseWaiterMessagList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WaiterMessagList extends BaseWaiterMessagList<WaiterMessagList> {
	public static final WaiterMessagList dao = new WaiterMessagList();
}
