package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseWithdrawalsApplyT;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WithdrawalsApplyT extends BaseWithdrawalsApplyT<WithdrawalsApplyT> {
	public static final WithdrawalsApplyT dao = new WithdrawalsApplyT();
}
