package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseWithdrawalsApply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WithdrawalsApply extends BaseWithdrawalsApply<WithdrawalsApply> {
	public static final WithdrawalsApply dao = new WithdrawalsApply();
}
