package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZAd;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZAd extends BaseZAd<ZAd> {
	public static final ZAd dao = new ZAd();
}
