package org.tgcloud.zhanzhang.entity;

import java.sql.Date;

import org.tgcloud.zhanzhang.entity.base.BaseZAdApplyDays;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZAdApplyDays extends BaseZAdApplyDays<ZAdApplyDays> {
	public ZAdApplyDays(Integer adApply_id, Date c) {
		// TODO Auto-generated constructor stub
		this.setAdApplyId(adApply_id);
		this.setDay(c);
	}

	public ZAdApplyDays() {
	}
	public static final ZAdApplyDays dao = new ZAdApplyDays();
}
