package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZAdApply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZAdApply extends BaseZAdApply<ZAdApply> {
	public static final ZAdApply dao = new ZAdApply();
}
