package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZAgriculture;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZAgriculture extends BaseZAgriculture<ZAgriculture> {
	public static final ZAgriculture dao = new ZAgriculture();
	
	public ZAgriculture(){
				
			}
	
	public ZAgriculture(String classify,int user_id,Integer city_id,Integer county_id,String location_x,String location_y,
    String type,Integer pricetype,String price,String priceunit,Integer startnumtype,Integer startnum,Integer havenum,String title,String content,String merits,
    String linkman,String tel,String imgs,Integer maintype,Integer isneed,Integer status){
		this.setClassify(classify);
		this.setUserId(user_id);
		this.setCityId(city_id);
		this.setCountyId(county_id);
		this.setLocationX(location_x);
		this.setLocationY(location_y);
		this.setType(type);
		this.setPricetype(pricetype);
		this.setPrice(price);
		this.setPriceunit(priceunit);
		this.setStartnumtype(startnumtype);
		this.setStartnum(startnum);
		this.setHavenum(havenum);
		this.setTitle(title);
		this.setContent(content);
		this.setMerits(merits);
		this.setLinkman(linkman);
		this.setTel(tel);
		this.setImgs(imgs);
		this.setStatus(status);
		this.setMaintype(maintype);
		this.setIsneed(isneed);
	}
	
	public ZAgriculture(String classify,int user_id,Integer city_id,Integer county_id,String location_x,String location_y,
		    String type,Integer pricetype,String price,String priceunit,Integer startnumtype,Integer startnum,Integer havenum,String title,String content,String merits,
		    String linkman,String tel,String imgs,Integer maintype,Integer tradetimetype,String tradetime,String tradetimeunit
		    ,Integer areatype,String area,String areaunit,String sheshi,String dipingzheng,String peitaojiju,String gaosu,String gangkou,String guodao
		    ,String tielu,String gaotie,String jichang,Integer isneed,Integer status){
				this.setClassify(classify);
				this.setUserId(user_id);
				this.setCityId(city_id);
				this.setCountyId(county_id);
				this.setLocationX(location_x);
				this.setLocationY(location_y);
				this.setType(type);
				this.setPricetype(pricetype);
				this.setPrice(price);
				this.setPriceunit(priceunit);
				this.setStartnumtype(startnumtype);
				this.setStartnum(startnum);
				this.setHavenum(havenum);
				this.setTitle(title);
				this.setContent(content);
				this.setMerits(merits);
				this.setLinkman(linkman);
				this.setTel(tel);
				this.setImgs(imgs);
				this.setStatus(status);
				this.setMaintype(maintype);
				this.setIsneed(isneed);
				this.setTradetime(tradetime);
				this.setTradetimetype(tradetimetype);
				this.setTradetimeunit(tradetimeunit);
				this.setArea(area);
				this.setAreatype(areatype);
				this.setAreaunit(areaunit);
				this.setSheshi(sheshi);
				this.setDipingzheng(dipingzheng);
				this.setPeitaojiju(peitaojiju);
				this.setGaosu(gaosu);
				this.setGangkou(gangkou);
				this.setGuodao(guodao);
				this.setTielu(tielu);
				this.setGaotie(gaotie);
				this.setJichang(jichang);
			}
}
