package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZcAdditional;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZcAdditional extends BaseZcAdditional<ZcAdditional> {
	public static final ZcAdditional dao = new ZcAdditional();
}
