package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZCards;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZCards extends BaseZCards<ZCards> {
	public static final ZCards dao = new ZCards();
}
