package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZcCarforpeople;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZcCarforpeople extends BaseZcCarforpeople<ZcCarforpeople> {
	public static final ZcCarforpeople dao = new ZcCarforpeople();
}
