package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZcCarandgoods;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZcCarandgoods extends BaseZcCarandgoods<ZcCarandgoods> {
	public static final ZcCarandgoods dao = new ZcCarandgoods();
}
