package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZcGoodsandcar;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZcGoodsandcar extends BaseZcGoodsandcar<ZcGoodsandcar> {
	public static final ZcGoodsandcar dao = new ZcGoodsandcar();
}
