package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZClickInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZClickInfo extends BaseZClickInfo<ZClickInfo> {
	public static final ZClickInfo dao = new ZClickInfo();
}
