package org.tgcloud.zhanzhang.entity;


import org.tgcloud.zhanzhang.entity.base.BaseZCompanyGoods;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZCompanyGoods extends BaseZCompanyGoods<ZCompanyGoods> {
	public ZCompanyGoods(String title, int user_id, int com_id, String etitle,
			String content, String imgs,int status) {
		// TODO Auto-generated constructor stub
		this.setTitle(title);
		this.setEtitle(etitle);
		this.setContent(content);
		this.setUserId(user_id);
		this.setComId(com_id);
		this.setStatus(1);	
		this.setImgs(imgs);
		this.setStatus(status);
	}

	public ZCompanyGoods() {
		// TODO Auto-generated constructor stub
	}
	public static final ZCompanyGoods dao = new ZCompanyGoods();
}
