package org.tgcloud.zhanzhang.entity;


import org.tgcloud.zhanzhang.entity.base.BaseZCompanyContact;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZCompanyContact extends BaseZCompanyContact<ZCompanyContact> {
	public ZCompanyContact(String email, int user_id, int com_id,
			String address, int iswork, String holiworkstart,
			String holiworkend) {
		// TODO Auto-generated constructor stub
		this.setEmail(email);
		this.setAddress(address);
		this.setIswork(iswork);
		this.setHoliworkstart(holiworkstart);
		this.setHoliworkend(holiworkend);
		this.setUserId(user_id);
		this.setComId(com_id);
		this.setStatus(1);	
	}

	public ZCompanyContact(){}
	public ZCompanyContact(Integer id, String email, int user_id, int com_id,
			String address, int iswork, String holiworkstart,
			String holiworkend) {
		this.setId(id);
		this.setEmail(email);
		this.setAddress(address);
		this.setIswork(iswork);
		this.setHoliworkstart(holiworkstart);
		this.setHoliworkend(holiworkend);
	}
	public static final ZCompanyContact dao = new ZCompanyContact();
}
