package org.tgcloud.zhanzhang.entity;


import org.tgcloud.zhanzhang.entity.base.BaseZCompanySupport;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZCompanySupport extends BaseZCompanySupport<ZCompanySupport> {
	public ZCompanySupport(int user_id, int com_id) {
		// TODO Auto-generated constructor stub
		this.setUserId(user_id);
		this.setComId(com_id);
		this.setStatus(1);	
	}
	public ZCompanySupport(int id,int user_id, int com_id) {
		// TODO Auto-generated constructor stub
		this.setUserId(user_id);
		this.setComId(com_id);
		this.setId(id);
	}
	public ZCompanySupport() {}
	
	public static final ZCompanySupport dao = new ZCompanySupport();
}
