package org.tgcloud.zhanzhang.entity;


import org.tgcloud.zhanzhang.entity.base.BaseZCompanyNews;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZCompanyNews extends BaseZCompanyNews<ZCompanyNews> {
	public ZCompanyNews(String title, int user_id, int com_id) {
		// TODO Auto-generated constructor stub
		this.setTitle(title);
		this.setUserId(user_id);
		this.setNums(0);
		this.setComId(com_id);
		this.setStatus(1);
	}

	public ZCompanyNews() {
	}
	
	public static final ZCompanyNews dao = new ZCompanyNews();
}
