package org.tgcloud.zhanzhang.entity;


import org.tgcloud.zhanzhang.entity.base.BaseZCompanyLink;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZCompanyLink extends BaseZCompanyLink<ZCompanyLink> {
	public ZCompanyLink(Integer contactId, String nikname, String tel) {
		// TODO Auto-generated constructor stub
		this.setContactId(contactId);
		this.setNikname(nikname);
		this.setTel(tel);
		this.setStatus(1);
	}
	
	public ZCompanyLink(){}

	public static final ZCompanyLink dao = new ZCompanyLink();
}
