package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.core.GlobalStatic;
import org.tgcloud.zhanzhang.entity.base.BaseZContextPath;

import java.sql.Date;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZContextPath extends BaseZContextPath<ZContextPath> {

	public static final ZContextPath dao = new ZContextPath();

	public ZContextPath() {
	}

	public ZContextPath(Integer scenic_id, String c_image, String c_context,int info_type) {
		this.setInfoId(scenic_id);
		this.setImgPath(c_image);
		this.setContent(c_context);
		this.setInfoType(info_type);
		this.setStatus(GlobalStatic.enabled);
	}
}
