package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZcPeoplecar;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZcPeoplecar extends BaseZcPeoplecar<ZcPeoplecar> {
	public static final ZcPeoplecar dao = new ZcPeoplecar();
}
