package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZCrowdShenfen;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZCrowdShenfen extends BaseZCrowdShenfen<ZCrowdShenfen> {
	public static final ZCrowdShenfen dao = new ZCrowdShenfen();
}
