package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZCrowdZhanghao;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZCrowdZhanghao extends BaseZCrowdZhanghao<ZCrowdZhanghao> {
	public static final ZCrowdZhanghao dao = new ZCrowdZhanghao();
}
