package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZCrowdDonate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZCrowdDonate extends BaseZCrowdDonate<ZCrowdDonate> {
	public static final ZCrowdDonate dao = new ZCrowdDonate();
}
