package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZCrowd;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZCrowd extends BaseZCrowd<ZCrowd> {
	public static final ZCrowd dao = new ZCrowd();
}
