package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZCrowdYiyuan;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZCrowdYiyuan extends BaseZCrowdYiyuan<ZCrowdYiyuan> {
	public static final ZCrowdYiyuan dao = new ZCrowdYiyuan();
}
