package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZCrowdHongshizi;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZCrowdHongshizi extends BaseZCrowdHongshizi<ZCrowdHongshizi> {
	public static final ZCrowdHongshizi dao = new ZCrowdHongshizi();
}
