package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZCrowdReply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZCrowdReply extends BaseZCrowdReply<ZCrowdReply> {
	public static final ZCrowdReply dao = new ZCrowdReply();
}
