package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZcTaxidriver;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZcTaxidriver extends BaseZcTaxidriver<ZcTaxidriver> {
	public static final ZcTaxidriver dao = new ZcTaxidriver();
}
