package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZcTaxi;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZcTaxi extends BaseZcTaxi<ZcTaxi> {
	public static final ZcTaxi dao = new ZcTaxi();
}
