package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZcTaxicompany;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZcTaxicompany extends BaseZcTaxicompany<ZcTaxicompany> {
	public static final ZcTaxicompany dao = new ZcTaxicompany();
}
