package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZcUsertrajectory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZcUsertrajectory extends BaseZcUsertrajectory<ZcUsertrajectory> {
	public static final ZcUsertrajectory dao = new ZcUsertrajectory();
}
