package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZcVehicle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZcVehicle extends BaseZcVehicle<ZcVehicle> {
	public static final ZcVehicle dao = new ZcVehicle();
}
