package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZFindworker;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZFindworker extends BaseZFindworker<ZFindworker> {
	public static final ZFindworker dao = new ZFindworker();
	public ZFindworker(){}
	public ZFindworker(String title,String nums,Integer sex,String age,int user_id,Integer province_id,
	Integer city_id,Integer county_id,String income,String choice,String restday,
    String worktime,String degrees,String remarks,String companyname,String trade,String introduce,
    String linkman,String tel,String imgs,Integer showtel,Integer showcontact,Integer status){
		this.setTitle(title);
		this.setNums(nums);
		this.setSex(sex);
		this.setAge(age);
		this.setUserId(user_id);
		this.setProvinceId(province_id);
		this.setCityId(city_id);
		this.setCountyId(county_id);
		this.setIncome(income);
		this.setChoice(choice);
		this.setWorktime(worktime);
		this.setRestday(restday);
		this.setDegrees(degrees);
		this.setTrade(trade);
		this.setRemarks(remarks);
		this.setCompanyname(companyname);
		this.setIntroduce(introduce);
		this.setLinkman(linkman);
		this.setTel(tel);
		this.setImgs(imgs);
		this.setShowtel(showtel);
		this.setShowcontact(showcontact);
		this.setStatus(status);
	}
}
