package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZImgPath;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZImgPath extends BaseZImgPath<ZImgPath> {
	public static final ZImgPath dao = new ZImgPath();
}
