package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZInfoUrl;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZInfoUrl extends BaseZInfoUrl<ZInfoUrl> {

	public static final ZInfoUrl dao = new ZInfoUrl();

    public ZInfoUrl() {
    }

    public ZInfoUrl(Integer info_id, String c_url, String url_content, int info_type) {
        this.setInfoId(info_id);
        this.setUrl(c_url);
        this.setContent(url_content);
        this.setInfoType(info_type);
    }
}
