package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZLocal;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZLocal extends BaseZLocal<ZLocal> {
	public static final ZLocal dao = new ZLocal();
}
