package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZManager;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZManager extends BaseZManager<ZManager> {
	public static final ZManager dao = new ZManager();
}
