package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZMasterScope;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZMasterScope extends BaseZMasterScope<ZMasterScope> {
	public static final ZMasterScope dao = new ZMasterScope();
}
