package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZMasterP;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZMasterP extends BaseZMasterP<ZMasterP> {
	public static final ZMasterP dao = new ZMasterP();
}
