package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZMaster;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZMaster extends BaseZMaster<ZMaster> {
	public static final ZMaster dao = new ZMaster();
}
