package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZMasterNotice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZMasterNotice extends BaseZMasterNotice<ZMasterNotice> {
	public static final ZMasterNotice dao = new ZMasterNotice();
}
