package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZMoneyOut;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZMoneyOut extends BaseZMoneyOut<ZMoneyOut> {
	public static final ZMoneyOut dao = new ZMoneyOut();
}
