package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZNoticeBaomingApply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZNoticeBaomingApply extends BaseZNoticeBaomingApply<ZNoticeBaomingApply> {
	public static final ZNoticeBaomingApply dao = new ZNoticeBaomingApply();
}
