package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZNoticeZhengqiu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZNoticeZhengqiu extends BaseZNoticeZhengqiu<ZNoticeZhengqiu> {
	public static final ZNoticeZhengqiu dao = new ZNoticeZhengqiu();
}
