package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZNoticeBaoming;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZNoticeBaoming extends BaseZNoticeBaoming<ZNoticeBaoming> {
	public static final ZNoticeBaoming dao = new ZNoticeBaoming();
}
