package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZNoticeFankui;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZNoticeFankui extends BaseZNoticeFankui<ZNoticeFankui> {
	public static final ZNoticeFankui dao = new ZNoticeFankui();
}
