package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZNoticePraise;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZNoticePraise extends BaseZNoticePraise<ZNoticePraise> {
	public static final ZNoticePraise dao = new ZNoticePraise();
	public ZNoticePraise() {
	}

    public ZNoticePraise(int user_id, int info_id, int info_type,int status) {
        this.setUserId(user_id);
        this.setInfoType(info_type);
        this.setInfoId(info_id);
        this.setStatus(status);
    }
}
