package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZNoticeQiuzheng;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZNoticeQiuzheng extends BaseZNoticeQiuzheng<ZNoticeQiuzheng> {
	public static final ZNoticeQiuzheng dao = new ZNoticeQiuzheng();
}
