package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZNoticeTongzhi;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZNoticeTongzhi extends BaseZNoticeTongzhi<ZNoticeTongzhi> {
	public static final ZNoticeTongzhi dao = new ZNoticeTongzhi();
}
