package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZNoticePinglun;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZNoticePinglun extends BaseZNoticePinglun<ZNoticePinglun> {
	public static final ZNoticePinglun dao = new ZNoticePinglun();
}
