package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZNoticeReply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZNoticeReply extends BaseZNoticeReply<ZNoticeReply> {
	public static final ZNoticeReply dao = new ZNoticeReply();
}
