package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZPay;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZPay extends BaseZPay<ZPay> {
	public static final ZPay dao = new ZPay();
}
