package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZPeopleNeed;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZPeopleNeed extends BaseZPeopleNeed<ZPeopleNeed> {
	public static final ZPeopleNeed dao = new ZPeopleNeed();
}
