package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZPeopleService;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZPeopleService extends BaseZPeopleService<ZPeopleService> {
	public static final ZPeopleService dao = new ZPeopleService();
}
