package org.tgcloud.zhanzhang.entity;

import java.sql.Date;

import org.tgcloud.zhanzhang.entity.base.BaseZPhonemsm;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZPhonemsm extends BaseZPhonemsm<ZPhonemsm> {
	public static final ZPhonemsm dao = new ZPhonemsm();
    public ZPhonemsm(String telephone, Integer type) {
        this.setTelephone(telephone);
        this.setType(type);
        this.setStatus(1);
        this.setSendStatus(2);
    }
    public ZPhonemsm() {
    }
}
