package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZPraiseInfo;

import java.sql.Date;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZPraiseInfo extends BaseZPraiseInfo<ZPraiseInfo> {

	public static final ZPraiseInfo dao = new ZPraiseInfo();

	public ZPraiseInfo() {
	}

    public ZPraiseInfo(int user_id, int info_id, int info_type) {
        this.setUserId(user_id);
        this.setInfoType(info_type);
        this.setInfoId(info_id);
    }
}
