package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZProductShow;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZProductShow extends BaseZProductShow<ZProductShow> {
	public static final ZProductShow dao = new ZProductShow();
}
