package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZProduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZProduct extends BaseZProduct<ZProduct> {
	public static final ZProduct dao = new ZProduct();
}
