package org.tgcloud.zhanzhang.entity;

import java.sql.Date;

import org.tgcloud.zhanzhang.entity.base.BaseZReportInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZReportInfo extends BaseZReportInfo<ZReportInfo> {
    public ZReportInfo() {
    }

    public ZReportInfo(int user_id, int info_id, int info_type) {
        this.setUserId(user_id);
        this.setInfoType(info_type);
        this.setInfoId(info_id);
    }
	public static final ZReportInfo dao = new ZReportInfo();
}
