package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZSearchInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZSearchInfo extends BaseZSearchInfo<ZSearchInfo> {
	public static final ZSearchInfo dao = new ZSearchInfo();
}
