package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZShuabingset;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZShuabingset extends BaseZShuabingset<ZShuabingset> {
	public static final ZShuabingset dao = new ZShuabingset();
}
