package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZStoreInfo;

import java.sql.Date;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZStoreInfo extends BaseZStoreInfo<ZStoreInfo> {

	public static final ZStoreInfo dao = new ZStoreInfo();

    public ZStoreInfo() {
    }

    public ZStoreInfo(int user_id, int info_id, int info_type) {
        this.setUserId(user_id);
        this.setInfoType(info_type);
        this.setInfoId(info_id);
    }
}
