package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZTCommentTable;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZTCommentTable extends BaseZTCommentTable<ZTCommentTable> {
	public static final ZTCommentTable dao = new ZTCommentTable();
}
