package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZTemporary;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZTemporary extends BaseZTemporary<ZTemporary> {
	public static final ZTemporary dao = new ZTemporary();
}
