package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZTravelGuide;

import java.math.BigDecimal;
import java.sql.Date;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZTravelGuide extends BaseZTravelGuide<ZTravelGuide> {

	public static final ZTravelGuide dao = new ZTravelGuide();

    public ZTravelGuide() {
    }

    public ZTravelGuide(int user_id, String username, Integer age, Integer sex, Integer price, Integer hours, Integer province_id, Integer city_id, Integer county_id, String configure, String places, String brand, String category, Integer car_price, Integer car_hours, String message, String telephone, Integer status,Integer car_c,String location_x, String location_y) {
        this.setUserId(user_id);
        this.setUsername(username);
        this.setAge(age);
        this.setSex(sex);
        this.setPrice(new BigDecimal(price));
        this.setHours(hours);
        this.setProvinceId(province_id);
        this.setCityId(city_id);
        this.setCountyId(county_id);
        this.setConfigure(configure);
        this.setPlaces(places);
        this.setCarBrand(brand);
        this.setCarCate(category);
        this.setCarPrice(new BigDecimal(car_price == null?0:car_price));
        this.setCarHours(car_hours);
        this.setMessage(message);
        this.setStatus(status);
        this.setTelephone(telephone);
        this.setCarC(car_c);
        this.setLocationX(location_x);
        this.setLocationX(location_y);
        this.setUserStatus(1);
    }
}
