package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZTravelScenic;

import java.sql.Date;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZTravelScenic extends BaseZTravelScenic<ZTravelScenic> {

	public static final ZTravelScenic dao = new ZTravelScenic();

    public ZTravelScenic() {
    }

    public ZTravelScenic(String main_img,String title, Integer show_status, int city_id, int province_id, int county_id, int status, int user_id, String location_x, String location_y) {
        this.setMainImg(main_img);
        this.setTitle(title);
        this.setShowStatus(show_status);
        this.setCityId(city_id);
        this.setCountyId(county_id);
        this.setProvinceId(province_id);
        this.setStatus(status);
        this.setUserId(user_id);
        this.setLocationY(location_y);
        this.setLocationX(location_x);
    }
}
