package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZUserPingbi;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZUserPingbi extends BaseZUserPingbi<ZUserPingbi> {
	public static final ZUserPingbi dao = new ZUserPingbi();
}
