package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZUserclickInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZUserclickInfo extends BaseZUserclickInfo<ZUserclickInfo> {
	public static final ZUserclickInfo dao = new ZUserclickInfo();
	public ZUserclickInfo() {
    }

    public ZUserclickInfo(int user_id, int info_id, int info_type) {
        this.setUserId(user_id);
        this.setInfoType(info_type);
        this.setInfoId(info_id);
    }
}
