package org.tgcloud.zhanzhang.entity;

import org.tgcloud.zhanzhang.entity.base.BaseZUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZUser extends BaseZUser<ZUser> {
	public static final ZUser dao = new ZUser();
}
